// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_element, unused_field
import 'dart:ffi' as ffi;

/// Auto-generated bindings for Delta Chat Core.
class DeltaChatBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  DeltaChatBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  DeltaChatBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  ffi.Pointer<dc_accounts_t> dc_accounts_new(
    ffi.Pointer<ffi.Char> dir,
    int writable,
  ) {
    return _dc_accounts_new(
      dir,
      writable,
    );
  }

  late final _dc_accounts_newPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_accounts_t> Function(
              ffi.Pointer<ffi.Char>, ffi.Int32)>>('dc_accounts_new');
  late final _dc_accounts_new = _dc_accounts_newPtr.asFunction<
      ffi.Pointer<dc_accounts_t> Function(ffi.Pointer<ffi.Char>, int)>();

  void dc_accounts_unref(
    ffi.Pointer<dc_accounts_t> accounts,
  ) {
    return _dc_accounts_unref(
      accounts,
    );
  }

  late final _dc_accounts_unrefPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dc_accounts_t>)>>(
      'dc_accounts_unref');
  late final _dc_accounts_unref = _dc_accounts_unrefPtr
      .asFunction<void Function(ffi.Pointer<dc_accounts_t>)>();

  int dc_accounts_add_account(
    ffi.Pointer<dc_accounts_t> accounts,
  ) {
    return _dc_accounts_add_account(
      accounts,
    );
  }

  late final _dc_accounts_add_accountPtr = _lookup<
          ffi.NativeFunction<ffi.Uint32 Function(ffi.Pointer<dc_accounts_t>)>>(
      'dc_accounts_add_account');
  late final _dc_accounts_add_account = _dc_accounts_add_accountPtr
      .asFunction<int Function(ffi.Pointer<dc_accounts_t>)>();

  int dc_accounts_add_closed_account(
    ffi.Pointer<dc_accounts_t> accounts,
  ) {
    return _dc_accounts_add_closed_account(
      accounts,
    );
  }

  late final _dc_accounts_add_closed_accountPtr = _lookup<
          ffi.NativeFunction<ffi.Uint32 Function(ffi.Pointer<dc_accounts_t>)>>(
      'dc_accounts_add_closed_account');
  late final _dc_accounts_add_closed_account =
      _dc_accounts_add_closed_accountPtr
          .asFunction<int Function(ffi.Pointer<dc_accounts_t>)>();

  int dc_accounts_migrate_account(
    ffi.Pointer<dc_accounts_t> accounts,
    ffi.Pointer<ffi.Char> dbfile,
  ) {
    return _dc_accounts_migrate_account(
      accounts,
      dbfile,
    );
  }

  late final _dc_accounts_migrate_accountPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint32 Function(ffi.Pointer<dc_accounts_t>,
              ffi.Pointer<ffi.Char>)>>('dc_accounts_migrate_account');
  late final _dc_accounts_migrate_account =
      _dc_accounts_migrate_accountPtr.asFunction<
          int Function(ffi.Pointer<dc_accounts_t>, ffi.Pointer<ffi.Char>)>();

  int dc_accounts_remove_account(
    ffi.Pointer<dc_accounts_t> accounts,
    int account_id,
  ) {
    return _dc_accounts_remove_account(
      accounts,
      account_id,
    );
  }

  late final _dc_accounts_remove_accountPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<dc_accounts_t>,
              ffi.Uint32)>>('dc_accounts_remove_account');
  late final _dc_accounts_remove_account = _dc_accounts_remove_accountPtr
      .asFunction<int Function(ffi.Pointer<dc_accounts_t>, int)>();

  ffi.Pointer<dc_array_t> dc_accounts_get_all(
    ffi.Pointer<dc_accounts_t> accounts,
  ) {
    return _dc_accounts_get_all(
      accounts,
    );
  }

  late final _dc_accounts_get_allPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_array_t> Function(
              ffi.Pointer<dc_accounts_t>)>>('dc_accounts_get_all');
  late final _dc_accounts_get_all = _dc_accounts_get_allPtr.asFunction<
      ffi.Pointer<dc_array_t> Function(ffi.Pointer<dc_accounts_t>)>();

  ffi.Pointer<dc_context_t> dc_accounts_get_account(
    ffi.Pointer<dc_accounts_t> accounts,
    int account_id,
  ) {
    return _dc_accounts_get_account(
      accounts,
      account_id,
    );
  }

  late final _dc_accounts_get_accountPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_context_t> Function(ffi.Pointer<dc_accounts_t>,
              ffi.Uint32)>>('dc_accounts_get_account');
  late final _dc_accounts_get_account = _dc_accounts_get_accountPtr.asFunction<
      ffi.Pointer<dc_context_t> Function(ffi.Pointer<dc_accounts_t>, int)>();

  void dc_accounts_start_io(
    ffi.Pointer<dc_accounts_t> accounts,
  ) {
    return _dc_accounts_start_io(
      accounts,
    );
  }

  late final _dc_accounts_start_ioPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dc_accounts_t>)>>(
      'dc_accounts_start_io');
  late final _dc_accounts_start_io = _dc_accounts_start_ioPtr
      .asFunction<void Function(ffi.Pointer<dc_accounts_t>)>();

  void dc_accounts_stop_io(
    ffi.Pointer<dc_accounts_t> accounts,
  ) {
    return _dc_accounts_stop_io(
      accounts,
    );
  }

  late final _dc_accounts_stop_ioPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dc_accounts_t>)>>(
      'dc_accounts_stop_io');
  late final _dc_accounts_stop_io = _dc_accounts_stop_ioPtr
      .asFunction<void Function(ffi.Pointer<dc_accounts_t>)>();

  void dc_accounts_maybe_network(
    ffi.Pointer<dc_accounts_t> accounts,
  ) {
    return _dc_accounts_maybe_network(
      accounts,
    );
  }

  late final _dc_accounts_maybe_networkPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dc_accounts_t>)>>(
      'dc_accounts_maybe_network');
  late final _dc_accounts_maybe_network = _dc_accounts_maybe_networkPtr
      .asFunction<void Function(ffi.Pointer<dc_accounts_t>)>();

  void dc_accounts_maybe_network_lost(
    ffi.Pointer<dc_accounts_t> accounts,
  ) {
    return _dc_accounts_maybe_network_lost(
      accounts,
    );
  }

  late final _dc_accounts_maybe_network_lostPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dc_accounts_t>)>>(
      'dc_accounts_maybe_network_lost');
  late final _dc_accounts_maybe_network_lost =
      _dc_accounts_maybe_network_lostPtr
          .asFunction<void Function(ffi.Pointer<dc_accounts_t>)>();

  int dc_accounts_background_fetch(
    ffi.Pointer<dc_accounts_t> accounts,
    int timeout,
  ) {
    return _dc_accounts_background_fetch(
      accounts,
      timeout,
    );
  }

  late final _dc_accounts_background_fetchPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<dc_accounts_t>,
              ffi.Uint64)>>('dc_accounts_background_fetch');
  late final _dc_accounts_background_fetch = _dc_accounts_background_fetchPtr
      .asFunction<int Function(ffi.Pointer<dc_accounts_t>, int)>();

  void dc_accounts_set_push_device_token(
    ffi.Pointer<dc_accounts_t> accounts,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _dc_accounts_set_push_device_token(
      accounts,
      token,
    );
  }

  late final _dc_accounts_set_push_device_tokenPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dc_accounts_t>,
              ffi.Pointer<ffi.Char>)>>('dc_accounts_set_push_device_token');
  late final _dc_accounts_set_push_device_token =
      _dc_accounts_set_push_device_tokenPtr.asFunction<
          void Function(ffi.Pointer<dc_accounts_t>, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<dc_event_emitter_t> dc_accounts_get_event_emitter(
    ffi.Pointer<dc_accounts_t> accounts,
  ) {
    return _dc_accounts_get_event_emitter(
      accounts,
    );
  }

  late final _dc_accounts_get_event_emitterPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_event_emitter_t> Function(
              ffi.Pointer<dc_accounts_t>)>>('dc_accounts_get_event_emitter');
  late final _dc_accounts_get_event_emitter =
      _dc_accounts_get_event_emitterPtr.asFunction<
          ffi.Pointer<dc_event_emitter_t> Function(
              ffi.Pointer<dc_accounts_t>)>();

  ffi.Pointer<dc_context_t> dc_context_new(
    ffi.Pointer<ffi.Char> os_name,
    ffi.Pointer<ffi.Char> dbfile,
    ffi.Pointer<ffi.Char> blobdir,
  ) {
    return _dc_context_new(
      os_name,
      dbfile,
      blobdir,
    );
  }

  late final _dc_context_newPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_context_t> Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>>('dc_context_new');
  late final _dc_context_new = _dc_context_newPtr.asFunction<
      ffi.Pointer<dc_context_t> Function(ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<dc_context_t> dc_context_new_closed(
    ffi.Pointer<ffi.Char> dbfile,
  ) {
    return _dc_context_new_closed(
      dbfile,
    );
  }

  late final _dc_context_new_closedPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_context_t> Function(
              ffi.Pointer<ffi.Char>)>>('dc_context_new_closed');
  late final _dc_context_new_closed = _dc_context_new_closedPtr
      .asFunction<ffi.Pointer<dc_context_t> Function(ffi.Pointer<ffi.Char>)>();

  void dc_context_unref(
    ffi.Pointer<dc_context_t> ctx,
  ) {
    return _dc_context_unref(
      ctx,
    );
  }

  late final _dc_context_unrefPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dc_context_t>)>>(
          'dc_context_unref');
  late final _dc_context_unref = _dc_context_unrefPtr
      .asFunction<void Function(ffi.Pointer<dc_context_t>)>();

  int dc_context_open(
    ffi.Pointer<dc_context_t> ctx,
    ffi.Pointer<ffi.Char> passphrase,
  ) {
    return _dc_context_open(
      ctx,
      passphrase,
    );
  }

  late final _dc_context_openPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<dc_context_t>,
              ffi.Pointer<ffi.Char>)>>('dc_context_open');
  late final _dc_context_open = _dc_context_openPtr.asFunction<
      int Function(ffi.Pointer<dc_context_t>, ffi.Pointer<ffi.Char>)>();

  int dc_context_change_passphrase(
    ffi.Pointer<dc_context_t> ctx,
    ffi.Pointer<ffi.Char> passphrase,
  ) {
    return _dc_context_change_passphrase(
      ctx,
      passphrase,
    );
  }

  late final _dc_context_change_passphrasePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<dc_context_t>,
              ffi.Pointer<ffi.Char>)>>('dc_context_change_passphrase');
  late final _dc_context_change_passphrase =
      _dc_context_change_passphrasePtr.asFunction<
          int Function(ffi.Pointer<dc_context_t>, ffi.Pointer<ffi.Char>)>();

  int dc_context_is_open(
    ffi.Pointer<dc_context_t> ctx,
  ) {
    return _dc_context_is_open(
      ctx,
    );
  }

  late final _dc_context_is_openPtr = _lookup<
          ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<dc_context_t>)>>(
      'dc_context_is_open');
  late final _dc_context_is_open = _dc_context_is_openPtr
      .asFunction<int Function(ffi.Pointer<dc_context_t>)>();

  int dc_is_configured(
    ffi.Pointer<dc_context_t> ctx,
  ) {
    return _dc_is_configured(
      ctx,
    );
  }

  late final _dc_is_configuredPtr = _lookup<
          ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<dc_context_t>)>>(
      'dc_is_configured');
  late final _dc_is_configured = _dc_is_configuredPtr
      .asFunction<int Function(ffi.Pointer<dc_context_t>)>();

  void dc_configure(
    ffi.Pointer<dc_context_t> ctx,
  ) {
    return _dc_configure(
      ctx,
    );
  }

  late final _dc_configurePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dc_context_t>)>>(
          'dc_configure');
  late final _dc_configure =
      _dc_configurePtr.asFunction<void Function(ffi.Pointer<dc_context_t>)>();

  int dc_set_config(
    ffi.Pointer<dc_context_t> ctx,
    ffi.Pointer<ffi.Char> key,
    ffi.Pointer<ffi.Char> value,
  ) {
    return _dc_set_config(
      ctx,
      key,
      value,
    );
  }

  late final _dc_set_configPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<dc_context_t>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('dc_set_config');
  late final _dc_set_config = _dc_set_configPtr.asFunction<
      int Function(ffi.Pointer<dc_context_t>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>)>();

  void dc_start_io(
    ffi.Pointer<dc_context_t> ctx,
  ) {
    return _dc_start_io(
      ctx,
    );
  }

  late final _dc_start_ioPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dc_context_t>)>>(
          'dc_start_io');
  late final _dc_start_io =
      _dc_start_ioPtr.asFunction<void Function(ffi.Pointer<dc_context_t>)>();

  void dc_stop_io(
    ffi.Pointer<dc_context_t> ctx,
  ) {
    return _dc_stop_io(
      ctx,
    );
  }

  late final _dc_stop_ioPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dc_context_t>)>>(
          'dc_stop_io');
  late final _dc_stop_io =
      _dc_stop_ioPtr.asFunction<void Function(ffi.Pointer<dc_context_t>)>();

  void dc_maybe_network(
    ffi.Pointer<dc_context_t> ctx,
  ) {
    return _dc_maybe_network(
      ctx,
    );
  }

  late final _dc_maybe_networkPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dc_context_t>)>>(
          'dc_maybe_network');
  late final _dc_maybe_network = _dc_maybe_networkPtr
      .asFunction<void Function(ffi.Pointer<dc_context_t>)>();

  ffi.Pointer<dc_event_emitter_t> dc_get_event_emitter(
    ffi.Pointer<dc_context_t> ctx,
  ) {
    return _dc_get_event_emitter(
      ctx,
    );
  }

  late final _dc_get_event_emitterPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_event_emitter_t> Function(
              ffi.Pointer<dc_context_t>)>>('dc_get_event_emitter');
  late final _dc_get_event_emitter = _dc_get_event_emitterPtr.asFunction<
      ffi.Pointer<dc_event_emitter_t> Function(ffi.Pointer<dc_context_t>)>();

  void dc_event_emitter_unref(
    ffi.Pointer<dc_event_emitter_t> emitter,
  ) {
    return _dc_event_emitter_unref(
      emitter,
    );
  }

  late final _dc_event_emitter_unrefPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Pointer<dc_event_emitter_t>)>>(
      'dc_event_emitter_unref');
  late final _dc_event_emitter_unref = _dc_event_emitter_unrefPtr
      .asFunction<void Function(ffi.Pointer<dc_event_emitter_t>)>();

  ffi.Pointer<dc_event_t> dc_get_next_event(
    ffi.Pointer<dc_event_emitter_t> emitter,
  ) {
    return _dc_get_next_event(
      emitter,
    );
  }

  late final _dc_get_next_eventPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_event_t> Function(
              ffi.Pointer<dc_event_emitter_t>)>>('dc_get_next_event');
  late final _dc_get_next_event = _dc_get_next_eventPtr.asFunction<
      ffi.Pointer<dc_event_t> Function(ffi.Pointer<dc_event_emitter_t>)>();

  void dc_event_unref(
    ffi.Pointer<dc_event_t> event,
  ) {
    return _dc_event_unref(
      event,
    );
  }

  late final _dc_event_unrefPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dc_event_t>)>>(
          'dc_event_unref');
  late final _dc_event_unref =
      _dc_event_unrefPtr.asFunction<void Function(ffi.Pointer<dc_event_t>)>();

  int dc_event_get_id(
    ffi.Pointer<dc_event_t> event,
  ) {
    return _dc_event_get_id(
      event,
    );
  }

  late final _dc_event_get_idPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<dc_event_t>)>>(
          'dc_event_get_id');
  late final _dc_event_get_id =
      _dc_event_get_idPtr.asFunction<int Function(ffi.Pointer<dc_event_t>)>();

  int dc_event_get_data1_int(
    ffi.Pointer<dc_event_t> event,
  ) {
    return _dc_event_get_data1_int(
      event,
    );
  }

  late final _dc_event_get_data1_intPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<dc_event_t>)>>(
          'dc_event_get_data1_int');
  late final _dc_event_get_data1_int = _dc_event_get_data1_intPtr
      .asFunction<int Function(ffi.Pointer<dc_event_t>)>();

  int dc_event_get_data2_int(
    ffi.Pointer<dc_event_t> event,
  ) {
    return _dc_event_get_data2_int(
      event,
    );
  }

  late final _dc_event_get_data2_intPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<dc_event_t>)>>(
          'dc_event_get_data2_int');
  late final _dc_event_get_data2_int = _dc_event_get_data2_intPtr
      .asFunction<int Function(ffi.Pointer<dc_event_t>)>();

  ffi.Pointer<ffi.Char> dc_event_get_data1_str(
    ffi.Pointer<dc_event_t> event,
  ) {
    return _dc_event_get_data1_str(
      event,
    );
  }

  late final _dc_event_get_data1_strPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<dc_event_t>)>>('dc_event_get_data1_str');
  late final _dc_event_get_data1_str = _dc_event_get_data1_strPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<dc_event_t>)>();

  ffi.Pointer<ffi.Char> dc_event_get_data2_str(
    ffi.Pointer<dc_event_t> event,
  ) {
    return _dc_event_get_data2_str(
      event,
    );
  }

  late final _dc_event_get_data2_strPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<dc_event_t>)>>('dc_event_get_data2_str');
  late final _dc_event_get_data2_str = _dc_event_get_data2_strPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<dc_event_t>)>();

  int dc_event_get_account_id(
    ffi.Pointer<dc_event_t> event,
  ) {
    return _dc_event_get_account_id(
      event,
    );
  }

  late final _dc_event_get_account_idPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function(ffi.Pointer<dc_event_t>)>>(
          'dc_event_get_account_id');
  late final _dc_event_get_account_id = _dc_event_get_account_idPtr
      .asFunction<int Function(ffi.Pointer<dc_event_t>)>();

  void dc_str_unref(
    ffi.Pointer<ffi.Char> value,
  ) {
    return _dc_str_unref(
      value,
    );
  }

  late final _dc_str_unrefPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
          'dc_str_unref');
  late final _dc_str_unref =
      _dc_str_unrefPtr.asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  void dc_array_unref(
    ffi.Pointer<dc_array_t> array,
  ) {
    return _dc_array_unref(
      array,
    );
  }

  late final _dc_array_unrefPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dc_array_t>)>>(
          'dc_array_unref');
  late final _dc_array_unref =
      _dc_array_unrefPtr.asFunction<void Function(ffi.Pointer<dc_array_t>)>();

  int dc_array_get_cnt(
    ffi.Pointer<dc_array_t> array,
  ) {
    return _dc_array_get_cnt(
      array,
    );
  }

  late final _dc_array_get_cntPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<dc_array_t>)>>(
          'dc_array_get_cnt');
  late final _dc_array_get_cnt =
      _dc_array_get_cntPtr.asFunction<int Function(ffi.Pointer<dc_array_t>)>();

  int dc_array_get_id(
    ffi.Pointer<dc_array_t> array,
    int index,
  ) {
    return _dc_array_get_id(
      array,
      index,
    );
  }

  late final _dc_array_get_idPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint32 Function(
              ffi.Pointer<dc_array_t>, ffi.Int32)>>('dc_array_get_id');
  late final _dc_array_get_id = _dc_array_get_idPtr
      .asFunction<int Function(ffi.Pointer<dc_array_t>, int)>();

  int dc_create_contact(
    ffi.Pointer<dc_context_t> ctx,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Char> addr,
  ) {
    return _dc_create_contact(
      ctx,
      name,
      addr,
    );
  }

  late final _dc_create_contactPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint32 Function(ffi.Pointer<dc_context_t>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('dc_create_contact');
  late final _dc_create_contact = _dc_create_contactPtr.asFunction<
      int Function(ffi.Pointer<dc_context_t>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>)>();

  int dc_create_chat_by_contact_id(
    ffi.Pointer<dc_context_t> ctx,
    int contact_id,
  ) {
    return _dc_create_chat_by_contact_id(
      ctx,
      contact_id,
    );
  }

  late final _dc_create_chat_by_contact_idPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint32 Function(ffi.Pointer<dc_context_t>,
              ffi.Uint32)>>('dc_create_chat_by_contact_id');
  late final _dc_create_chat_by_contact_id = _dc_create_chat_by_contact_idPtr
      .asFunction<int Function(ffi.Pointer<dc_context_t>, int)>();

  int dc_send_text_msg(
    ffi.Pointer<dc_context_t> ctx,
    int chat_id,
    ffi.Pointer<ffi.Char> text,
  ) {
    return _dc_send_text_msg(
      ctx,
      chat_id,
      text,
    );
  }

  late final _dc_send_text_msgPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint32 Function(ffi.Pointer<dc_context_t>, ffi.Uint32,
              ffi.Pointer<ffi.Char>)>>('dc_send_text_msg');
  late final _dc_send_text_msg = _dc_send_text_msgPtr.asFunction<
      int Function(ffi.Pointer<dc_context_t>, int, ffi.Pointer<ffi.Char>)>();

  int dc_send_msg(
    ffi.Pointer<dc_context_t> ctx,
    int chat_id,
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_send_msg(
      ctx,
      chat_id,
      msg,
    );
  }

  late final _dc_send_msgPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint32 Function(ffi.Pointer<dc_context_t>, ffi.Uint32,
              ffi.Pointer<dc_msg_t>)>>('dc_send_msg');
  late final _dc_send_msg = _dc_send_msgPtr.asFunction<
      int Function(ffi.Pointer<dc_context_t>, int, ffi.Pointer<dc_msg_t>)>();

  ffi.Pointer<dc_chat_t> dc_get_chat(
    ffi.Pointer<dc_context_t> ctx,
    int chat_id,
  ) {
    return _dc_get_chat(
      ctx,
      chat_id,
    );
  }

  late final _dc_get_chatPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_chat_t> Function(
              ffi.Pointer<dc_context_t>, ffi.Uint32)>>('dc_get_chat');
  late final _dc_get_chat = _dc_get_chatPtr.asFunction<
      ffi.Pointer<dc_chat_t> Function(ffi.Pointer<dc_context_t>, int)>();

  void dc_chat_unref(
    ffi.Pointer<dc_chat_t> chat,
  ) {
    return _dc_chat_unref(
      chat,
    );
  }

  late final _dc_chat_unrefPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dc_chat_t>)>>(
          'dc_chat_unref');
  late final _dc_chat_unref =
      _dc_chat_unrefPtr.asFunction<void Function(ffi.Pointer<dc_chat_t>)>();

  ffi.Pointer<ffi.Char> dc_chat_get_name(
    ffi.Pointer<dc_chat_t> chat,
  ) {
    return _dc_chat_get_name(
      chat,
    );
  }

  late final _dc_chat_get_namePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<dc_chat_t>)>>('dc_chat_get_name');
  late final _dc_chat_get_name = _dc_chat_get_namePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<dc_chat_t>)>();

  ffi.Pointer<ffi.Char> dc_chat_get_mailinglist_addr(
    ffi.Pointer<dc_chat_t> chat,
  ) {
    return _dc_chat_get_mailinglist_addr(
      chat,
    );
  }

  late final _dc_chat_get_mailinglist_addrPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<dc_chat_t>)>>('dc_chat_get_mailinglist_addr');
  late final _dc_chat_get_mailinglist_addr = _dc_chat_get_mailinglist_addrPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<dc_chat_t>)>();

  int dc_chat_get_type(
    ffi.Pointer<dc_chat_t> chat,
  ) {
    return _dc_chat_get_type(
      chat,
    );
  }

  late final _dc_chat_get_typePtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<dc_chat_t>)>>(
          'dc_chat_get_type');
  late final _dc_chat_get_type =
      _dc_chat_get_typePtr.asFunction<int Function(ffi.Pointer<dc_chat_t>)>();

  int dc_chat_get_contact_id(
    ffi.Pointer<dc_chat_t> chat,
  ) {
    return _dc_chat_get_contact_id(
      chat,
    );
  }

  late final _dc_chat_get_contact_idPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function(ffi.Pointer<dc_chat_t>)>>(
          'dc_chat_get_contact_id');
  late final _dc_chat_get_contact_id = _dc_chat_get_contact_idPtr
      .asFunction<int Function(ffi.Pointer<dc_chat_t>)>();

  ffi.Pointer<dc_contact_t> dc_get_contact(
    ffi.Pointer<dc_context_t> ctx,
    int contact_id,
  ) {
    return _dc_get_contact(
      ctx,
      contact_id,
    );
  }

  late final _dc_get_contactPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_contact_t> Function(
              ffi.Pointer<dc_context_t>, ffi.Uint32)>>('dc_get_contact');
  late final _dc_get_contact = _dc_get_contactPtr.asFunction<
      ffi.Pointer<dc_contact_t> Function(ffi.Pointer<dc_context_t>, int)>();

  void dc_contact_unref(
    ffi.Pointer<dc_contact_t> contact,
  ) {
    return _dc_contact_unref(
      contact,
    );
  }

  late final _dc_contact_unrefPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dc_contact_t>)>>(
          'dc_contact_unref');
  late final _dc_contact_unref = _dc_contact_unrefPtr
      .asFunction<void Function(ffi.Pointer<dc_contact_t>)>();

  ffi.Pointer<ffi.Char> dc_contact_get_addr(
    ffi.Pointer<dc_contact_t> contact,
  ) {
    return _dc_contact_get_addr(
      contact,
    );
  }

  late final _dc_contact_get_addrPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<dc_contact_t>)>>('dc_contact_get_addr');
  late final _dc_contact_get_addr = _dc_contact_get_addrPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<dc_contact_t>)>();

  ffi.Pointer<ffi.Char> dc_contact_get_name(
    ffi.Pointer<dc_contact_t> contact,
  ) {
    return _dc_contact_get_name(
      contact,
    );
  }

  late final _dc_contact_get_namePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<dc_contact_t>)>>('dc_contact_get_name');
  late final _dc_contact_get_name = _dc_contact_get_namePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<dc_contact_t>)>();

  ffi.Pointer<dc_msg_t> dc_get_msg(
    ffi.Pointer<dc_context_t> ctx,
    int msg_id,
  ) {
    return _dc_get_msg(
      ctx,
      msg_id,
    );
  }

  late final _dc_get_msgPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_msg_t> Function(
              ffi.Pointer<dc_context_t>, ffi.Uint32)>>('dc_get_msg');
  late final _dc_get_msg = _dc_get_msgPtr.asFunction<
      ffi.Pointer<dc_msg_t> Function(ffi.Pointer<dc_context_t>, int)>();

  void dc_msg_unref(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_unref(
      msg,
    );
  }

  late final _dc_msg_unrefPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dc_msg_t>)>>(
          'dc_msg_unref');
  late final _dc_msg_unref =
      _dc_msg_unrefPtr.asFunction<void Function(ffi.Pointer<dc_msg_t>)>();

  ffi.Pointer<ffi.Char> dc_msg_get_text(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_get_text(
      msg,
    );
  }

  late final _dc_msg_get_textPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<dc_msg_t>)>>('dc_msg_get_text');
  late final _dc_msg_get_text = _dc_msg_get_textPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<dc_msg_t>)>();

  int dc_msg_get_chat_id(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_get_chat_id(
      msg,
    );
  }

  late final _dc_msg_get_chat_idPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function(ffi.Pointer<dc_msg_t>)>>(
          'dc_msg_get_chat_id');
  late final _dc_msg_get_chat_id =
      _dc_msg_get_chat_idPtr.asFunction<int Function(ffi.Pointer<dc_msg_t>)>();

  int dc_msg_get_id(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_get_id(
      msg,
    );
  }

  late final _dc_msg_get_idPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function(ffi.Pointer<dc_msg_t>)>>(
          'dc_msg_get_id');
  late final _dc_msg_get_id =
      _dc_msg_get_idPtr.asFunction<int Function(ffi.Pointer<dc_msg_t>)>();

  int dc_msg_get_viewtype(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_get_viewtype(
      msg,
    );
  }

  late final _dc_msg_get_viewtypePtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<dc_msg_t>)>>(
          'dc_msg_get_viewtype');
  late final _dc_msg_get_viewtype =
      _dc_msg_get_viewtypePtr.asFunction<int Function(ffi.Pointer<dc_msg_t>)>();

  int dc_msg_get_timestamp(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_get_timestamp(
      msg,
    );
  }

  late final _dc_msg_get_timestampPtr =
      _lookup<ffi.NativeFunction<ffi.Uint64 Function(ffi.Pointer<dc_msg_t>)>>(
          'dc_msg_get_timestamp');
  late final _dc_msg_get_timestamp = _dc_msg_get_timestampPtr
      .asFunction<int Function(ffi.Pointer<dc_msg_t>)>();

  int dc_msg_is_outgoing(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_is_outgoing(
      msg,
    );
  }

  late final _dc_msg_is_outgoingPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<dc_msg_t>)>>(
          'dc_msg_is_outgoing');
  late final _dc_msg_is_outgoing =
      _dc_msg_is_outgoingPtr.asFunction<int Function(ffi.Pointer<dc_msg_t>)>();

  ffi.Pointer<dc_msg_t> dc_msg_new(
    ffi.Pointer<dc_context_t> ctx,
    int viewtype,
  ) {
    return _dc_msg_new(
      ctx,
      viewtype,
    );
  }

  late final _dc_msg_newPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_msg_t> Function(
              ffi.Pointer<dc_context_t>, ffi.Int32)>>('dc_msg_new');
  late final _dc_msg_new = _dc_msg_newPtr.asFunction<
      ffi.Pointer<dc_msg_t> Function(ffi.Pointer<dc_context_t>, int)>();

  void dc_msg_set_text(
    ffi.Pointer<dc_msg_t> msg,
    ffi.Pointer<ffi.Char> text,
  ) {
    return _dc_msg_set_text(
      msg,
      text,
    );
  }

  late final _dc_msg_set_textPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dc_msg_t>,
              ffi.Pointer<ffi.Char>)>>('dc_msg_set_text');
  late final _dc_msg_set_text = _dc_msg_set_textPtr.asFunction<
      void Function(ffi.Pointer<dc_msg_t>, ffi.Pointer<ffi.Char>)>();

  void dc_msg_set_file_and_deduplicate(
    ffi.Pointer<dc_msg_t> msg,
    ffi.Pointer<ffi.Char> file,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Char> filemime,
  ) {
    return _dc_msg_set_file_and_deduplicate(
      msg,
      file,
      name,
      filemime,
    );
  }

  late final _dc_msg_set_file_and_deduplicatePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<dc_msg_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('dc_msg_set_file_and_deduplicate');
  late final _dc_msg_set_file_and_deduplicate =
      _dc_msg_set_file_and_deduplicatePtr.asFunction<
          void Function(ffi.Pointer<dc_msg_t>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> dc_msg_get_file(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_get_file(
      msg,
    );
  }

  late final _dc_msg_get_filePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<dc_msg_t>)>>('dc_msg_get_file');
  late final _dc_msg_get_file = _dc_msg_get_filePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<dc_msg_t>)>();

  ffi.Pointer<ffi.Char> dc_msg_get_filename(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_get_filename(
      msg,
    );
  }

  late final _dc_msg_get_filenamePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<dc_msg_t>)>>('dc_msg_get_filename');
  late final _dc_msg_get_filename = _dc_msg_get_filenamePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<dc_msg_t>)>();

  ffi.Pointer<ffi.Char> dc_msg_get_filemime(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_get_filemime(
      msg,
    );
  }

  late final _dc_msg_get_filemimePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<dc_msg_t>)>>('dc_msg_get_filemime');
  late final _dc_msg_get_filemime = _dc_msg_get_filemimePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<dc_msg_t>)>();

  int dc_msg_get_filebytes(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_get_filebytes(
      msg,
    );
  }

  late final _dc_msg_get_filebytesPtr =
      _lookup<ffi.NativeFunction<ffi.Uint64 Function(ffi.Pointer<dc_msg_t>)>>(
          'dc_msg_get_filebytes');
  late final _dc_msg_get_filebytes = _dc_msg_get_filebytesPtr
      .asFunction<int Function(ffi.Pointer<dc_msg_t>)>();

  int dc_msg_get_width(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_get_width(
      msg,
    );
  }

  late final _dc_msg_get_widthPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<dc_msg_t>)>>(
          'dc_msg_get_width');
  late final _dc_msg_get_width =
      _dc_msg_get_widthPtr.asFunction<int Function(ffi.Pointer<dc_msg_t>)>();

  int dc_msg_get_height(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_get_height(
      msg,
    );
  }

  late final _dc_msg_get_heightPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<dc_msg_t>)>>(
          'dc_msg_get_height');
  late final _dc_msg_get_height =
      _dc_msg_get_heightPtr.asFunction<int Function(ffi.Pointer<dc_msg_t>)>();
}

final class __mbstate_t extends ffi.Union {
  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> __mbstate8;

  @ffi.LongLong()
  external int _mbstateL;
}

final class __darwin_pthread_handler_rec extends ffi.Struct {
  external ffi
      .Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>
      __routine;

  external ffi.Pointer<ffi.Void> __arg;

  external ffi.Pointer<__darwin_pthread_handler_rec> __next;
}

final class _opaque_pthread_attr_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_cond_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([40])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_condattr_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_mutex_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_mutexattr_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_once_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_rwlock_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([192])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_rwlockattr_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([16])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  external ffi.Pointer<__darwin_pthread_handler_rec> __cleanup_stack;

  @ffi.Array.multi([8176])
  external ffi.Array<ffi.Char> __opaque;
}

final class dc_context extends ffi.Opaque {}

final class dc_accounts extends ffi.Opaque {}

final class dc_array extends ffi.Opaque {}

final class dc_event extends ffi.Opaque {}

final class dc_event_emitter extends ffi.Opaque {}

final class dc_chat extends ffi.Opaque {}

final class dc_contact extends ffi.Opaque {}

final class dc_msg extends ffi.Opaque {}

typedef dc_context_t = dc_context;
typedef dc_event_emitter_t = dc_event_emitter;
typedef dc_event_t = dc_event;
typedef dc_msg_t = dc_msg;
typedef dc_chat_t = dc_chat;
typedef dc_contact_t = dc_contact;
typedef dc_accounts_t = dc_accounts;
typedef dc_array_t = dc_array;

const int __WORDSIZE = 64;

const int __has_safe_buffers = 1;

const int __DARWIN_ONLY_64_BIT_INO_T = 1;

const int __DARWIN_ONLY_UNIX_CONFORMANCE = 1;

const int __DARWIN_ONLY_VERS_1050 = 1;

const int __DARWIN_UNIX03 = 1;

const int __DARWIN_64_BIT_INO_T = 1;

const int __DARWIN_VERS_1050 = 1;

const int __DARWIN_NON_CANCELABLE = 0;

const String __DARWIN_SUF_EXTSN = '\$DARWIN_EXTSN';

const int __DARWIN_C_ANSI = 4096;

const int __DARWIN_C_FULL = 900000;

const int __DARWIN_C_LEVEL = 900000;

const int __STDC_WANT_LIB_EXT1__ = 1;

const int __DARWIN_NO_LONG_LONG = 0;

const int _DARWIN_FEATURE_64_BIT_INODE = 1;

const int _DARWIN_FEATURE_ONLY_64_BIT_INODE = 1;

const int _DARWIN_FEATURE_ONLY_VERS_1050 = 1;

const int _DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE = 1;

const int _DARWIN_FEATURE_UNIX_CONFORMANCE = 3;

const int __has_ptrcheck = 0;

const int __DARWIN_NULL = 0;

const int __PTHREAD_SIZE__ = 8176;

const int __PTHREAD_ATTR_SIZE__ = 56;

const int __PTHREAD_MUTEXATTR_SIZE__ = 8;

const int __PTHREAD_MUTEX_SIZE__ = 56;

const int __PTHREAD_CONDATTR_SIZE__ = 8;

const int __PTHREAD_COND_SIZE__ = 40;

const int __PTHREAD_ONCE_SIZE__ = 8;

const int __PTHREAD_RWLOCK_SIZE__ = 192;

const int __PTHREAD_RWLOCKATTR_SIZE__ = 16;

const int INT8_MAX = 127;

const int INT16_MAX = 32767;

const int INT32_MAX = 2147483647;

const int INT64_MAX = 9223372036854775807;

const int INT8_MIN = -128;

const int INT16_MIN = -32768;

const int INT32_MIN = -2147483648;

const int INT64_MIN = -9223372036854775808;

const int UINT8_MAX = 255;

const int UINT16_MAX = 65535;

const int UINT32_MAX = 4294967295;

const int UINT64_MAX = -1;

const int INT_LEAST8_MIN = -128;

const int INT_LEAST16_MIN = -32768;

const int INT_LEAST32_MIN = -2147483648;

const int INT_LEAST64_MIN = -9223372036854775808;

const int INT_LEAST8_MAX = 127;

const int INT_LEAST16_MAX = 32767;

const int INT_LEAST32_MAX = 2147483647;

const int INT_LEAST64_MAX = 9223372036854775807;

const int UINT_LEAST8_MAX = 255;

const int UINT_LEAST16_MAX = 65535;

const int UINT_LEAST32_MAX = 4294967295;

const int UINT_LEAST64_MAX = -1;

const int INT_FAST8_MIN = -128;

const int INT_FAST16_MIN = -32768;

const int INT_FAST32_MIN = -2147483648;

const int INT_FAST64_MIN = -9223372036854775808;

const int INT_FAST8_MAX = 127;

const int INT_FAST16_MAX = 32767;

const int INT_FAST32_MAX = 2147483647;

const int INT_FAST64_MAX = 9223372036854775807;

const int UINT_FAST8_MAX = 255;

const int UINT_FAST16_MAX = 65535;

const int UINT_FAST32_MAX = 4294967295;

const int UINT_FAST64_MAX = -1;

const int INTPTR_MAX = 9223372036854775807;

const int INTPTR_MIN = -9223372036854775808;

const int UINTPTR_MAX = -1;

const int INTMAX_MAX = 9223372036854775807;

const int UINTMAX_MAX = -1;

const int INTMAX_MIN = -9223372036854775808;

const int PTRDIFF_MIN = -9223372036854775808;

const int PTRDIFF_MAX = 9223372036854775807;

const int SIZE_MAX = -1;

const int RSIZE_MAX = 9223372036854775807;

const int WCHAR_MAX = 2147483647;

const int WCHAR_MIN = -2147483648;

const int WINT_MIN = -2147483648;

const int WINT_MAX = 2147483647;

const int SIG_ATOMIC_MIN = -2147483648;

const int SIG_ATOMIC_MAX = 2147483647;

const int DC_MSG_TEXT = 10;

const int DC_MSG_IMAGE = 20;

const int DC_MSG_GIF = 21;

const int DC_MSG_AUDIO = 40;

const int DC_MSG_VOICE = 41;

const int DC_MSG_VIDEO = 50;

const int DC_MSG_FILE = 60;

const int DC_CHAT_TYPE_UNDEFINED = 0;

const int DC_CHAT_TYPE_SINGLE = 100;

const int DC_CHAT_TYPE_GROUP = 200;

const int DC_CHAT_TYPE_VERIFIED_GROUP = 300;

const int DC_CHAT_TYPE_BROADCAST = 400;

const int DC_EVENT_CONFIGURE_PROGRESS = 2041;
