// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Auto-generated bindings for Delta Chat Core.
class DeltaChatBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  DeltaChatBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  DeltaChatBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  ffi.Pointer<dc_accounts_t> dc_accounts_new(
    ffi.Pointer<ffi.Char> dir,
    int writable,
  ) {
    return _dc_accounts_new(
      dir,
      writable,
    );
  }

  late final _dc_accounts_newPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_accounts_t> Function(
              ffi.Pointer<ffi.Char>, ffi.Int32)>>('dc_accounts_new');
  late final _dc_accounts_new = _dc_accounts_newPtr.asFunction<
      ffi.Pointer<dc_accounts_t> Function(ffi.Pointer<ffi.Char>, int)>();

  void dc_accounts_unref(
    ffi.Pointer<dc_accounts_t> accounts,
  ) {
    return _dc_accounts_unref(
      accounts,
    );
  }

  late final _dc_accounts_unrefPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dc_accounts_t>)>>(
      'dc_accounts_unref');
  late final _dc_accounts_unref = _dc_accounts_unrefPtr
      .asFunction<void Function(ffi.Pointer<dc_accounts_t>)>();

  int dc_accounts_add_account(
    ffi.Pointer<dc_accounts_t> accounts,
  ) {
    return _dc_accounts_add_account(
      accounts,
    );
  }

  late final _dc_accounts_add_accountPtr = _lookup<
          ffi.NativeFunction<ffi.Uint32 Function(ffi.Pointer<dc_accounts_t>)>>(
      'dc_accounts_add_account');
  late final _dc_accounts_add_account = _dc_accounts_add_accountPtr
      .asFunction<int Function(ffi.Pointer<dc_accounts_t>)>();

  int dc_accounts_add_closed_account(
    ffi.Pointer<dc_accounts_t> accounts,
  ) {
    return _dc_accounts_add_closed_account(
      accounts,
    );
  }

  late final _dc_accounts_add_closed_accountPtr = _lookup<
          ffi.NativeFunction<ffi.Uint32 Function(ffi.Pointer<dc_accounts_t>)>>(
      'dc_accounts_add_closed_account');
  late final _dc_accounts_add_closed_account =
      _dc_accounts_add_closed_accountPtr
          .asFunction<int Function(ffi.Pointer<dc_accounts_t>)>();

  int dc_accounts_migrate_account(
    ffi.Pointer<dc_accounts_t> accounts,
    ffi.Pointer<ffi.Char> dbfile,
  ) {
    return _dc_accounts_migrate_account(
      accounts,
      dbfile,
    );
  }

  late final _dc_accounts_migrate_accountPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint32 Function(ffi.Pointer<dc_accounts_t>,
              ffi.Pointer<ffi.Char>)>>('dc_accounts_migrate_account');
  late final _dc_accounts_migrate_account =
      _dc_accounts_migrate_accountPtr.asFunction<
          int Function(ffi.Pointer<dc_accounts_t>, ffi.Pointer<ffi.Char>)>();

  int dc_accounts_remove_account(
    ffi.Pointer<dc_accounts_t> accounts,
    int account_id,
  ) {
    return _dc_accounts_remove_account(
      accounts,
      account_id,
    );
  }

  late final _dc_accounts_remove_accountPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<dc_accounts_t>,
              ffi.Uint32)>>('dc_accounts_remove_account');
  late final _dc_accounts_remove_account = _dc_accounts_remove_accountPtr
      .asFunction<int Function(ffi.Pointer<dc_accounts_t>, int)>();

  ffi.Pointer<dc_array_t> dc_accounts_get_all(
    ffi.Pointer<dc_accounts_t> accounts,
  ) {
    return _dc_accounts_get_all(
      accounts,
    );
  }

  late final _dc_accounts_get_allPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_array_t> Function(
              ffi.Pointer<dc_accounts_t>)>>('dc_accounts_get_all');
  late final _dc_accounts_get_all = _dc_accounts_get_allPtr.asFunction<
      ffi.Pointer<dc_array_t> Function(ffi.Pointer<dc_accounts_t>)>();

  ffi.Pointer<dc_context_t> dc_accounts_get_account(
    ffi.Pointer<dc_accounts_t> accounts,
    int account_id,
  ) {
    return _dc_accounts_get_account(
      accounts,
      account_id,
    );
  }

  late final _dc_accounts_get_accountPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_context_t> Function(ffi.Pointer<dc_accounts_t>,
              ffi.Uint32)>>('dc_accounts_get_account');
  late final _dc_accounts_get_account = _dc_accounts_get_accountPtr.asFunction<
      ffi.Pointer<dc_context_t> Function(ffi.Pointer<dc_accounts_t>, int)>();

  void dc_accounts_start_io(
    ffi.Pointer<dc_accounts_t> accounts,
  ) {
    return _dc_accounts_start_io(
      accounts,
    );
  }

  late final _dc_accounts_start_ioPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dc_accounts_t>)>>(
      'dc_accounts_start_io');
  late final _dc_accounts_start_io = _dc_accounts_start_ioPtr
      .asFunction<void Function(ffi.Pointer<dc_accounts_t>)>();

  void dc_accounts_stop_io(
    ffi.Pointer<dc_accounts_t> accounts,
  ) {
    return _dc_accounts_stop_io(
      accounts,
    );
  }

  late final _dc_accounts_stop_ioPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dc_accounts_t>)>>(
      'dc_accounts_stop_io');
  late final _dc_accounts_stop_io = _dc_accounts_stop_ioPtr
      .asFunction<void Function(ffi.Pointer<dc_accounts_t>)>();

  void dc_accounts_maybe_network(
    ffi.Pointer<dc_accounts_t> accounts,
  ) {
    return _dc_accounts_maybe_network(
      accounts,
    );
  }

  late final _dc_accounts_maybe_networkPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dc_accounts_t>)>>(
      'dc_accounts_maybe_network');
  late final _dc_accounts_maybe_network = _dc_accounts_maybe_networkPtr
      .asFunction<void Function(ffi.Pointer<dc_accounts_t>)>();

  void dc_accounts_maybe_network_lost(
    ffi.Pointer<dc_accounts_t> accounts,
  ) {
    return _dc_accounts_maybe_network_lost(
      accounts,
    );
  }

  late final _dc_accounts_maybe_network_lostPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dc_accounts_t>)>>(
      'dc_accounts_maybe_network_lost');
  late final _dc_accounts_maybe_network_lost =
      _dc_accounts_maybe_network_lostPtr
          .asFunction<void Function(ffi.Pointer<dc_accounts_t>)>();

  int dc_accounts_background_fetch(
    ffi.Pointer<dc_accounts_t> accounts,
    int timeout,
  ) {
    return _dc_accounts_background_fetch(
      accounts,
      timeout,
    );
  }

  late final _dc_accounts_background_fetchPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<dc_accounts_t>,
              ffi.Uint64)>>('dc_accounts_background_fetch');
  late final _dc_accounts_background_fetch = _dc_accounts_background_fetchPtr
      .asFunction<int Function(ffi.Pointer<dc_accounts_t>, int)>();

  void dc_accounts_set_push_device_token(
    ffi.Pointer<dc_accounts_t> accounts,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _dc_accounts_set_push_device_token(
      accounts,
      token,
    );
  }

  late final _dc_accounts_set_push_device_tokenPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dc_accounts_t>,
              ffi.Pointer<ffi.Char>)>>('dc_accounts_set_push_device_token');
  late final _dc_accounts_set_push_device_token =
      _dc_accounts_set_push_device_tokenPtr.asFunction<
          void Function(ffi.Pointer<dc_accounts_t>, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<dc_event_emitter_t> dc_accounts_get_event_emitter(
    ffi.Pointer<dc_accounts_t> accounts,
  ) {
    return _dc_accounts_get_event_emitter(
      accounts,
    );
  }

  late final _dc_accounts_get_event_emitterPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_event_emitter_t> Function(
              ffi.Pointer<dc_accounts_t>)>>('dc_accounts_get_event_emitter');
  late final _dc_accounts_get_event_emitter =
      _dc_accounts_get_event_emitterPtr.asFunction<
          ffi.Pointer<dc_event_emitter_t> Function(
              ffi.Pointer<dc_accounts_t>)>();

  ffi.Pointer<dc_context_t> dc_context_new(
    ffi.Pointer<ffi.Char> os_name,
    ffi.Pointer<ffi.Char> dbfile,
    ffi.Pointer<ffi.Char> blobdir,
  ) {
    return _dc_context_new(
      os_name,
      dbfile,
      blobdir,
    );
  }

  late final _dc_context_newPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_context_t> Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>>('dc_context_new');
  late final _dc_context_new = _dc_context_newPtr.asFunction<
      ffi.Pointer<dc_context_t> Function(ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<dc_context_t> dc_context_new_closed(
    ffi.Pointer<ffi.Char> dbfile,
  ) {
    return _dc_context_new_closed(
      dbfile,
    );
  }

  late final _dc_context_new_closedPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_context_t> Function(
              ffi.Pointer<ffi.Char>)>>('dc_context_new_closed');
  late final _dc_context_new_closed = _dc_context_new_closedPtr
      .asFunction<ffi.Pointer<dc_context_t> Function(ffi.Pointer<ffi.Char>)>();

  void dc_context_unref(
    ffi.Pointer<dc_context_t> ctx,
  ) {
    return _dc_context_unref(
      ctx,
    );
  }

  late final _dc_context_unrefPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dc_context_t>)>>(
          'dc_context_unref');
  late final _dc_context_unref = _dc_context_unrefPtr
      .asFunction<void Function(ffi.Pointer<dc_context_t>)>();

  int dc_context_open(
    ffi.Pointer<dc_context_t> ctx,
    ffi.Pointer<ffi.Char> passphrase,
  ) {
    return _dc_context_open(
      ctx,
      passphrase,
    );
  }

  late final _dc_context_openPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<dc_context_t>,
              ffi.Pointer<ffi.Char>)>>('dc_context_open');
  late final _dc_context_open = _dc_context_openPtr.asFunction<
      int Function(ffi.Pointer<dc_context_t>, ffi.Pointer<ffi.Char>)>();

  int dc_context_change_passphrase(
    ffi.Pointer<dc_context_t> ctx,
    ffi.Pointer<ffi.Char> passphrase,
  ) {
    return _dc_context_change_passphrase(
      ctx,
      passphrase,
    );
  }

  late final _dc_context_change_passphrasePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<dc_context_t>,
              ffi.Pointer<ffi.Char>)>>('dc_context_change_passphrase');
  late final _dc_context_change_passphrase =
      _dc_context_change_passphrasePtr.asFunction<
          int Function(ffi.Pointer<dc_context_t>, ffi.Pointer<ffi.Char>)>();

  int dc_context_is_open(
    ffi.Pointer<dc_context_t> ctx,
  ) {
    return _dc_context_is_open(
      ctx,
    );
  }

  late final _dc_context_is_openPtr = _lookup<
          ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<dc_context_t>)>>(
      'dc_context_is_open');
  late final _dc_context_is_open = _dc_context_is_openPtr
      .asFunction<int Function(ffi.Pointer<dc_context_t>)>();

  int dc_is_configured(
    ffi.Pointer<dc_context_t> ctx,
  ) {
    return _dc_is_configured(
      ctx,
    );
  }

  late final _dc_is_configuredPtr = _lookup<
          ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<dc_context_t>)>>(
      'dc_is_configured');
  late final _dc_is_configured = _dc_is_configuredPtr
      .asFunction<int Function(ffi.Pointer<dc_context_t>)>();

  void dc_configure(
    ffi.Pointer<dc_context_t> ctx,
  ) {
    return _dc_configure(
      ctx,
    );
  }

  late final _dc_configurePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dc_context_t>)>>(
          'dc_configure');
  late final _dc_configure =
      _dc_configurePtr.asFunction<void Function(ffi.Pointer<dc_context_t>)>();

  int dc_set_config(
    ffi.Pointer<dc_context_t> ctx,
    ffi.Pointer<ffi.Char> key,
    ffi.Pointer<ffi.Char> value,
  ) {
    return _dc_set_config(
      ctx,
      key,
      value,
    );
  }

  late final _dc_set_configPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<dc_context_t>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('dc_set_config');
  late final _dc_set_config = _dc_set_configPtr.asFunction<
      int Function(ffi.Pointer<dc_context_t>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>)>();

  void dc_start_io(
    ffi.Pointer<dc_context_t> ctx,
  ) {
    return _dc_start_io(
      ctx,
    );
  }

  late final _dc_start_ioPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dc_context_t>)>>(
          'dc_start_io');
  late final _dc_start_io =
      _dc_start_ioPtr.asFunction<void Function(ffi.Pointer<dc_context_t>)>();

  void dc_stop_io(
    ffi.Pointer<dc_context_t> ctx,
  ) {
    return _dc_stop_io(
      ctx,
    );
  }

  late final _dc_stop_ioPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dc_context_t>)>>(
          'dc_stop_io');
  late final _dc_stop_io =
      _dc_stop_ioPtr.asFunction<void Function(ffi.Pointer<dc_context_t>)>();

  void dc_maybe_network(
    ffi.Pointer<dc_context_t> ctx,
  ) {
    return _dc_maybe_network(
      ctx,
    );
  }

  late final _dc_maybe_networkPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dc_context_t>)>>(
          'dc_maybe_network');
  late final _dc_maybe_network = _dc_maybe_networkPtr
      .asFunction<void Function(ffi.Pointer<dc_context_t>)>();

  int dc_get_connectivity(
    ffi.Pointer<dc_context_t> ctx,
  ) {
    return _dc_get_connectivity(
      ctx,
    );
  }

  late final _dc_get_connectivityPtr = _lookup<
          ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<dc_context_t>)>>(
      'dc_get_connectivity');
  late final _dc_get_connectivity = _dc_get_connectivityPtr
      .asFunction<int Function(ffi.Pointer<dc_context_t>)>();

  ffi.Pointer<ffi.Char> dc_get_last_error(
    ffi.Pointer<dc_context_t> ctx,
  ) {
    return _dc_get_last_error(
      ctx,
    );
  }

  late final _dc_get_last_errorPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<dc_context_t>)>>('dc_get_last_error');
  late final _dc_get_last_error = _dc_get_last_errorPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<dc_context_t>)>();

  ffi.Pointer<dc_chatlist_t> dc_get_chatlist(
    ffi.Pointer<dc_context_t> ctx,
    int flags,
    ffi.Pointer<ffi.Char> query_str,
    int query_id,
  ) {
    return _dc_get_chatlist(
      ctx,
      flags,
      query_str,
      query_id,
    );
  }

  late final _dc_get_chatlistPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_chatlist_t> Function(ffi.Pointer<dc_context_t>,
              ffi.Int, ffi.Pointer<ffi.Char>, ffi.Uint32)>>('dc_get_chatlist');
  late final _dc_get_chatlist = _dc_get_chatlistPtr.asFunction<
      ffi.Pointer<dc_chatlist_t> Function(
          ffi.Pointer<dc_context_t>, int, ffi.Pointer<ffi.Char>, int)>();

  void dc_chatlist_unref(
    ffi.Pointer<dc_chatlist_t> chatlist,
  ) {
    return _dc_chatlist_unref(
      chatlist,
    );
  }

  late final _dc_chatlist_unrefPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dc_chatlist_t>)>>(
      'dc_chatlist_unref');
  late final _dc_chatlist_unref = _dc_chatlist_unrefPtr
      .asFunction<void Function(ffi.Pointer<dc_chatlist_t>)>();

  int dc_chatlist_get_cnt(
    ffi.Pointer<dc_chatlist_t> chatlist,
  ) {
    return _dc_chatlist_get_cnt(
      chatlist,
    );
  }

  late final _dc_chatlist_get_cntPtr = _lookup<
          ffi.NativeFunction<ffi.Size Function(ffi.Pointer<dc_chatlist_t>)>>(
      'dc_chatlist_get_cnt');
  late final _dc_chatlist_get_cnt = _dc_chatlist_get_cntPtr
      .asFunction<int Function(ffi.Pointer<dc_chatlist_t>)>();

  int dc_chatlist_get_chat_id(
    ffi.Pointer<dc_chatlist_t> chatlist,
    int index,
  ) {
    return _dc_chatlist_get_chat_id(
      chatlist,
      index,
    );
  }

  late final _dc_chatlist_get_chat_idPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint32 Function(ffi.Pointer<dc_chatlist_t>,
              ffi.Size)>>('dc_chatlist_get_chat_id');
  late final _dc_chatlist_get_chat_id = _dc_chatlist_get_chat_idPtr
      .asFunction<int Function(ffi.Pointer<dc_chatlist_t>, int)>();

  int dc_chatlist_get_msg_id(
    ffi.Pointer<dc_chatlist_t> chatlist,
    int index,
  ) {
    return _dc_chatlist_get_msg_id(
      chatlist,
      index,
    );
  }

  late final _dc_chatlist_get_msg_idPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint32 Function(
              ffi.Pointer<dc_chatlist_t>, ffi.Size)>>('dc_chatlist_get_msg_id');
  late final _dc_chatlist_get_msg_id = _dc_chatlist_get_msg_idPtr
      .asFunction<int Function(ffi.Pointer<dc_chatlist_t>, int)>();

  ffi.Pointer<dc_array_t> dc_get_chat_msgs(
    ffi.Pointer<dc_context_t> ctx,
    int chat_id,
    int flags,
    int marker1before,
  ) {
    return _dc_get_chat_msgs(
      ctx,
      chat_id,
      flags,
      marker1before,
    );
  }

  late final _dc_get_chat_msgsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_array_t> Function(ffi.Pointer<dc_context_t>,
              ffi.Uint32, ffi.Uint32, ffi.Uint32)>>('dc_get_chat_msgs');
  late final _dc_get_chat_msgs = _dc_get_chat_msgsPtr.asFunction<
      ffi.Pointer<dc_array_t> Function(
          ffi.Pointer<dc_context_t>, int, int, int)>();

  int dc_get_msg_cnt(
    ffi.Pointer<dc_context_t> ctx,
    int chat_id,
  ) {
    return _dc_get_msg_cnt(
      ctx,
      chat_id,
    );
  }

  late final _dc_get_msg_cntPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<dc_context_t>, ffi.Uint32)>>('dc_get_msg_cnt');
  late final _dc_get_msg_cnt = _dc_get_msg_cntPtr
      .asFunction<int Function(ffi.Pointer<dc_context_t>, int)>();

  ffi.Pointer<dc_event_emitter_t> dc_get_event_emitter(
    ffi.Pointer<dc_context_t> ctx,
  ) {
    return _dc_get_event_emitter(
      ctx,
    );
  }

  late final _dc_get_event_emitterPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_event_emitter_t> Function(
              ffi.Pointer<dc_context_t>)>>('dc_get_event_emitter');
  late final _dc_get_event_emitter = _dc_get_event_emitterPtr.asFunction<
      ffi.Pointer<dc_event_emitter_t> Function(ffi.Pointer<dc_context_t>)>();

  void dc_event_emitter_unref(
    ffi.Pointer<dc_event_emitter_t> emitter,
  ) {
    return _dc_event_emitter_unref(
      emitter,
    );
  }

  late final _dc_event_emitter_unrefPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Pointer<dc_event_emitter_t>)>>(
      'dc_event_emitter_unref');
  late final _dc_event_emitter_unref = _dc_event_emitter_unrefPtr
      .asFunction<void Function(ffi.Pointer<dc_event_emitter_t>)>();

  ffi.Pointer<dc_event_t> dc_get_next_event(
    ffi.Pointer<dc_event_emitter_t> emitter,
  ) {
    return _dc_get_next_event(
      emitter,
    );
  }

  late final _dc_get_next_eventPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_event_t> Function(
              ffi.Pointer<dc_event_emitter_t>)>>('dc_get_next_event');
  late final _dc_get_next_event = _dc_get_next_eventPtr.asFunction<
      ffi.Pointer<dc_event_t> Function(ffi.Pointer<dc_event_emitter_t>)>();

  void dc_event_unref(
    ffi.Pointer<dc_event_t> event,
  ) {
    return _dc_event_unref(
      event,
    );
  }

  late final _dc_event_unrefPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dc_event_t>)>>(
          'dc_event_unref');
  late final _dc_event_unref =
      _dc_event_unrefPtr.asFunction<void Function(ffi.Pointer<dc_event_t>)>();

  int dc_event_get_id(
    ffi.Pointer<dc_event_t> event,
  ) {
    return _dc_event_get_id(
      event,
    );
  }

  late final _dc_event_get_idPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<dc_event_t>)>>(
          'dc_event_get_id');
  late final _dc_event_get_id =
      _dc_event_get_idPtr.asFunction<int Function(ffi.Pointer<dc_event_t>)>();

  int dc_event_get_data1_int(
    ffi.Pointer<dc_event_t> event,
  ) {
    return _dc_event_get_data1_int(
      event,
    );
  }

  late final _dc_event_get_data1_intPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<dc_event_t>)>>(
          'dc_event_get_data1_int');
  late final _dc_event_get_data1_int = _dc_event_get_data1_intPtr
      .asFunction<int Function(ffi.Pointer<dc_event_t>)>();

  int dc_event_get_data2_int(
    ffi.Pointer<dc_event_t> event,
  ) {
    return _dc_event_get_data2_int(
      event,
    );
  }

  late final _dc_event_get_data2_intPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<dc_event_t>)>>(
          'dc_event_get_data2_int');
  late final _dc_event_get_data2_int = _dc_event_get_data2_intPtr
      .asFunction<int Function(ffi.Pointer<dc_event_t>)>();

  ffi.Pointer<ffi.Char> dc_event_get_data1_str(
    ffi.Pointer<dc_event_t> event,
  ) {
    return _dc_event_get_data1_str(
      event,
    );
  }

  late final _dc_event_get_data1_strPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<dc_event_t>)>>('dc_event_get_data1_str');
  late final _dc_event_get_data1_str = _dc_event_get_data1_strPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<dc_event_t>)>();

  ffi.Pointer<ffi.Char> dc_event_get_data2_str(
    ffi.Pointer<dc_event_t> event,
  ) {
    return _dc_event_get_data2_str(
      event,
    );
  }

  late final _dc_event_get_data2_strPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<dc_event_t>)>>('dc_event_get_data2_str');
  late final _dc_event_get_data2_str = _dc_event_get_data2_strPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<dc_event_t>)>();

  int dc_event_get_account_id(
    ffi.Pointer<dc_event_t> event,
  ) {
    return _dc_event_get_account_id(
      event,
    );
  }

  late final _dc_event_get_account_idPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function(ffi.Pointer<dc_event_t>)>>(
          'dc_event_get_account_id');
  late final _dc_event_get_account_id = _dc_event_get_account_idPtr
      .asFunction<int Function(ffi.Pointer<dc_event_t>)>();

  void dc_str_unref(
    ffi.Pointer<ffi.Char> value,
  ) {
    return _dc_str_unref(
      value,
    );
  }

  late final _dc_str_unrefPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
          'dc_str_unref');
  late final _dc_str_unref =
      _dc_str_unrefPtr.asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  void dc_array_unref(
    ffi.Pointer<dc_array_t> array,
  ) {
    return _dc_array_unref(
      array,
    );
  }

  late final _dc_array_unrefPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dc_array_t>)>>(
          'dc_array_unref');
  late final _dc_array_unref =
      _dc_array_unrefPtr.asFunction<void Function(ffi.Pointer<dc_array_t>)>();

  int dc_array_get_cnt(
    ffi.Pointer<dc_array_t> array,
  ) {
    return _dc_array_get_cnt(
      array,
    );
  }

  late final _dc_array_get_cntPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<dc_array_t>)>>(
          'dc_array_get_cnt');
  late final _dc_array_get_cnt =
      _dc_array_get_cntPtr.asFunction<int Function(ffi.Pointer<dc_array_t>)>();

  int dc_array_get_id(
    ffi.Pointer<dc_array_t> array,
    int index,
  ) {
    return _dc_array_get_id(
      array,
      index,
    );
  }

  late final _dc_array_get_idPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint32 Function(
              ffi.Pointer<dc_array_t>, ffi.Int32)>>('dc_array_get_id');
  late final _dc_array_get_id = _dc_array_get_idPtr
      .asFunction<int Function(ffi.Pointer<dc_array_t>, int)>();

  int dc_create_contact(
    ffi.Pointer<dc_context_t> ctx,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Char> addr,
  ) {
    return _dc_create_contact(
      ctx,
      name,
      addr,
    );
  }

  late final _dc_create_contactPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint32 Function(ffi.Pointer<dc_context_t>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('dc_create_contact');
  late final _dc_create_contact = _dc_create_contactPtr.asFunction<
      int Function(ffi.Pointer<dc_context_t>, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>)>();

  int dc_create_chat_by_contact_id(
    ffi.Pointer<dc_context_t> ctx,
    int contact_id,
  ) {
    return _dc_create_chat_by_contact_id(
      ctx,
      contact_id,
    );
  }

  late final _dc_create_chat_by_contact_idPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint32 Function(ffi.Pointer<dc_context_t>,
              ffi.Uint32)>>('dc_create_chat_by_contact_id');
  late final _dc_create_chat_by_contact_id = _dc_create_chat_by_contact_idPtr
      .asFunction<int Function(ffi.Pointer<dc_context_t>, int)>();

  int dc_send_text_msg(
    ffi.Pointer<dc_context_t> ctx,
    int chat_id,
    ffi.Pointer<ffi.Char> text,
  ) {
    return _dc_send_text_msg(
      ctx,
      chat_id,
      text,
    );
  }

  late final _dc_send_text_msgPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint32 Function(ffi.Pointer<dc_context_t>, ffi.Uint32,
              ffi.Pointer<ffi.Char>)>>('dc_send_text_msg');
  late final _dc_send_text_msg = _dc_send_text_msgPtr.asFunction<
      int Function(ffi.Pointer<dc_context_t>, int, ffi.Pointer<ffi.Char>)>();

  int dc_send_msg(
    ffi.Pointer<dc_context_t> ctx,
    int chat_id,
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_send_msg(
      ctx,
      chat_id,
      msg,
    );
  }

  late final _dc_send_msgPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint32 Function(ffi.Pointer<dc_context_t>, ffi.Uint32,
              ffi.Pointer<dc_msg_t>)>>('dc_send_msg');
  late final _dc_send_msg = _dc_send_msgPtr.asFunction<
      int Function(ffi.Pointer<dc_context_t>, int, ffi.Pointer<dc_msg_t>)>();

  ffi.Pointer<dc_chat_t> dc_get_chat(
    ffi.Pointer<dc_context_t> ctx,
    int chat_id,
  ) {
    return _dc_get_chat(
      ctx,
      chat_id,
    );
  }

  late final _dc_get_chatPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_chat_t> Function(
              ffi.Pointer<dc_context_t>, ffi.Uint32)>>('dc_get_chat');
  late final _dc_get_chat = _dc_get_chatPtr.asFunction<
      ffi.Pointer<dc_chat_t> Function(ffi.Pointer<dc_context_t>, int)>();

  void dc_chat_unref(
    ffi.Pointer<dc_chat_t> chat,
  ) {
    return _dc_chat_unref(
      chat,
    );
  }

  late final _dc_chat_unrefPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dc_chat_t>)>>(
          'dc_chat_unref');
  late final _dc_chat_unref =
      _dc_chat_unrefPtr.asFunction<void Function(ffi.Pointer<dc_chat_t>)>();

  ffi.Pointer<ffi.Char> dc_chat_get_name(
    ffi.Pointer<dc_chat_t> chat,
  ) {
    return _dc_chat_get_name(
      chat,
    );
  }

  late final _dc_chat_get_namePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<dc_chat_t>)>>('dc_chat_get_name');
  late final _dc_chat_get_name = _dc_chat_get_namePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<dc_chat_t>)>();

  ffi.Pointer<ffi.Char> dc_chat_get_mailinglist_addr(
    ffi.Pointer<dc_chat_t> chat,
  ) {
    return _dc_chat_get_mailinglist_addr(
      chat,
    );
  }

  late final _dc_chat_get_mailinglist_addrPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<dc_chat_t>)>>('dc_chat_get_mailinglist_addr');
  late final _dc_chat_get_mailinglist_addr = _dc_chat_get_mailinglist_addrPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<dc_chat_t>)>();

  int dc_chat_get_type(
    ffi.Pointer<dc_chat_t> chat,
  ) {
    return _dc_chat_get_type(
      chat,
    );
  }

  late final _dc_chat_get_typePtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<dc_chat_t>)>>(
          'dc_chat_get_type');
  late final _dc_chat_get_type =
      _dc_chat_get_typePtr.asFunction<int Function(ffi.Pointer<dc_chat_t>)>();

  int dc_chat_get_contact_id(
    ffi.Pointer<dc_chat_t> chat,
  ) {
    return _dc_chat_get_contact_id(
      chat,
    );
  }

  late final _dc_chat_get_contact_idPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function(ffi.Pointer<dc_chat_t>)>>(
          'dc_chat_get_contact_id');
  late final _dc_chat_get_contact_id = _dc_chat_get_contact_idPtr
      .asFunction<int Function(ffi.Pointer<dc_chat_t>)>();

  ffi.Pointer<dc_array_t> dc_get_chat_contacts(
    ffi.Pointer<dc_context_t> ctx,
    int chat_id,
  ) {
    return _dc_get_chat_contacts(
      ctx,
      chat_id,
    );
  }

  late final _dc_get_chat_contactsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_array_t> Function(
              ffi.Pointer<dc_context_t>, ffi.Uint32)>>('dc_get_chat_contacts');
  late final _dc_get_chat_contacts = _dc_get_chat_contactsPtr.asFunction<
      ffi.Pointer<dc_array_t> Function(ffi.Pointer<dc_context_t>, int)>();

  ffi.Pointer<dc_contact_t> dc_get_contact(
    ffi.Pointer<dc_context_t> ctx,
    int contact_id,
  ) {
    return _dc_get_contact(
      ctx,
      contact_id,
    );
  }

  late final _dc_get_contactPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_contact_t> Function(
              ffi.Pointer<dc_context_t>, ffi.Uint32)>>('dc_get_contact');
  late final _dc_get_contact = _dc_get_contactPtr.asFunction<
      ffi.Pointer<dc_contact_t> Function(ffi.Pointer<dc_context_t>, int)>();

  void dc_contact_unref(
    ffi.Pointer<dc_contact_t> contact,
  ) {
    return _dc_contact_unref(
      contact,
    );
  }

  late final _dc_contact_unrefPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dc_contact_t>)>>(
          'dc_contact_unref');
  late final _dc_contact_unref = _dc_contact_unrefPtr
      .asFunction<void Function(ffi.Pointer<dc_contact_t>)>();

  ffi.Pointer<ffi.Char> dc_contact_get_addr(
    ffi.Pointer<dc_contact_t> contact,
  ) {
    return _dc_contact_get_addr(
      contact,
    );
  }

  late final _dc_contact_get_addrPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<dc_contact_t>)>>('dc_contact_get_addr');
  late final _dc_contact_get_addr = _dc_contact_get_addrPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<dc_contact_t>)>();

  ffi.Pointer<ffi.Char> dc_contact_get_name(
    ffi.Pointer<dc_contact_t> contact,
  ) {
    return _dc_contact_get_name(
      contact,
    );
  }

  late final _dc_contact_get_namePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<dc_contact_t>)>>('dc_contact_get_name');
  late final _dc_contact_get_name = _dc_contact_get_namePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<dc_contact_t>)>();

  int dc_block_contact(
    ffi.Pointer<dc_context_t> ctx,
    int contact_id,
  ) {
    return _dc_block_contact(
      ctx,
      contact_id,
    );
  }

  late final _dc_block_contactPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<dc_context_t>, ffi.Uint32)>>('dc_block_contact');
  late final _dc_block_contact = _dc_block_contactPtr
      .asFunction<int Function(ffi.Pointer<dc_context_t>, int)>();

  int dc_unblock_contact(
    ffi.Pointer<dc_context_t> ctx,
    int contact_id,
  ) {
    return _dc_unblock_contact(
      ctx,
      contact_id,
    );
  }

  late final _dc_unblock_contactPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<dc_context_t>, ffi.Uint32)>>('dc_unblock_contact');
  late final _dc_unblock_contact = _dc_unblock_contactPtr
      .asFunction<int Function(ffi.Pointer<dc_context_t>, int)>();

  int dc_lookup_contact_id_by_addr(
    ffi.Pointer<dc_context_t> ctx,
    ffi.Pointer<ffi.Char> addr,
  ) {
    return _dc_lookup_contact_id_by_addr(
      ctx,
      addr,
    );
  }

  late final _dc_lookup_contact_id_by_addrPtr = _lookup<
      ffi.NativeFunction<
          ffi.Uint32 Function(ffi.Pointer<dc_context_t>,
              ffi.Pointer<ffi.Char>)>>('dc_lookup_contact_id_by_addr');
  late final _dc_lookup_contact_id_by_addr =
      _dc_lookup_contact_id_by_addrPtr.asFunction<
          int Function(ffi.Pointer<dc_context_t>, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<dc_msg_t> dc_get_msg(
    ffi.Pointer<dc_context_t> ctx,
    int msg_id,
  ) {
    return _dc_get_msg(
      ctx,
      msg_id,
    );
  }

  late final _dc_get_msgPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_msg_t> Function(
              ffi.Pointer<dc_context_t>, ffi.Uint32)>>('dc_get_msg');
  late final _dc_get_msg = _dc_get_msgPtr.asFunction<
      ffi.Pointer<dc_msg_t> Function(ffi.Pointer<dc_context_t>, int)>();

  void dc_msg_unref(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_unref(
      msg,
    );
  }

  late final _dc_msg_unrefPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dc_msg_t>)>>(
          'dc_msg_unref');
  late final _dc_msg_unref =
      _dc_msg_unrefPtr.asFunction<void Function(ffi.Pointer<dc_msg_t>)>();

  ffi.Pointer<ffi.Char> dc_msg_get_text(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_get_text(
      msg,
    );
  }

  late final _dc_msg_get_textPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<dc_msg_t>)>>('dc_msg_get_text');
  late final _dc_msg_get_text = _dc_msg_get_textPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<dc_msg_t>)>();

  ffi.Pointer<ffi.Char> dc_msg_get_html(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_get_html(
      msg,
    );
  }

  late final _dc_msg_get_htmlPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<dc_msg_t>)>>('dc_msg_get_html');
  late final _dc_msg_get_html = _dc_msg_get_htmlPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<dc_msg_t>)>();

  ffi.Pointer<ffi.Char> dc_msg_get_subject(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_get_subject(
      msg,
    );
  }

  late final _dc_msg_get_subjectPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<dc_msg_t>)>>('dc_msg_get_subject');
  late final _dc_msg_get_subject = _dc_msg_get_subjectPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<dc_msg_t>)>();

  int dc_msg_get_chat_id(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_get_chat_id(
      msg,
    );
  }

  late final _dc_msg_get_chat_idPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function(ffi.Pointer<dc_msg_t>)>>(
          'dc_msg_get_chat_id');
  late final _dc_msg_get_chat_id =
      _dc_msg_get_chat_idPtr.asFunction<int Function(ffi.Pointer<dc_msg_t>)>();

  int dc_msg_get_id(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_get_id(
      msg,
    );
  }

  late final _dc_msg_get_idPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function(ffi.Pointer<dc_msg_t>)>>(
          'dc_msg_get_id');
  late final _dc_msg_get_id =
      _dc_msg_get_idPtr.asFunction<int Function(ffi.Pointer<dc_msg_t>)>();

  int dc_msg_get_viewtype(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_get_viewtype(
      msg,
    );
  }

  late final _dc_msg_get_viewtypePtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<dc_msg_t>)>>(
          'dc_msg_get_viewtype');
  late final _dc_msg_get_viewtype =
      _dc_msg_get_viewtypePtr.asFunction<int Function(ffi.Pointer<dc_msg_t>)>();

  int dc_msg_get_timestamp(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_get_timestamp(
      msg,
    );
  }

  late final _dc_msg_get_timestampPtr =
      _lookup<ffi.NativeFunction<ffi.Uint64 Function(ffi.Pointer<dc_msg_t>)>>(
          'dc_msg_get_timestamp');
  late final _dc_msg_get_timestamp = _dc_msg_get_timestampPtr
      .asFunction<int Function(ffi.Pointer<dc_msg_t>)>();

  int dc_msg_is_outgoing(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_is_outgoing(
      msg,
    );
  }

  late final _dc_msg_is_outgoingPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<dc_msg_t>)>>(
          'dc_msg_is_outgoing');
  late final _dc_msg_is_outgoing =
      _dc_msg_is_outgoingPtr.asFunction<int Function(ffi.Pointer<dc_msg_t>)>();

  int dc_msg_get_state(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_get_state(
      msg,
    );
  }

  late final _dc_msg_get_statePtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<dc_msg_t>)>>(
          'dc_msg_get_state');
  late final _dc_msg_get_state =
      _dc_msg_get_statePtr.asFunction<int Function(ffi.Pointer<dc_msg_t>)>();

  ffi.Pointer<dc_msg_t> dc_msg_new(
    ffi.Pointer<dc_context_t> ctx,
    int viewtype,
  ) {
    return _dc_msg_new(
      ctx,
      viewtype,
    );
  }

  late final _dc_msg_newPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_msg_t> Function(
              ffi.Pointer<dc_context_t>, ffi.Int32)>>('dc_msg_new');
  late final _dc_msg_new = _dc_msg_newPtr.asFunction<
      ffi.Pointer<dc_msg_t> Function(ffi.Pointer<dc_context_t>, int)>();

  void dc_msg_set_text(
    ffi.Pointer<dc_msg_t> msg,
    ffi.Pointer<ffi.Char> text,
  ) {
    return _dc_msg_set_text(
      msg,
      text,
    );
  }

  late final _dc_msg_set_textPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dc_msg_t>,
              ffi.Pointer<ffi.Char>)>>('dc_msg_set_text');
  late final _dc_msg_set_text = _dc_msg_set_textPtr.asFunction<
      void Function(ffi.Pointer<dc_msg_t>, ffi.Pointer<ffi.Char>)>();

  void dc_msg_set_html(
    ffi.Pointer<dc_msg_t> msg,
    ffi.Pointer<ffi.Char> html,
  ) {
    return _dc_msg_set_html(
      msg,
      html,
    );
  }

  late final _dc_msg_set_htmlPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dc_msg_t>,
              ffi.Pointer<ffi.Char>)>>('dc_msg_set_html');
  late final _dc_msg_set_html = _dc_msg_set_htmlPtr.asFunction<
      void Function(ffi.Pointer<dc_msg_t>, ffi.Pointer<ffi.Char>)>();

  void dc_msg_set_subject(
    ffi.Pointer<dc_msg_t> msg,
    ffi.Pointer<ffi.Char> subject,
  ) {
    return _dc_msg_set_subject(
      msg,
      subject,
    );
  }

  late final _dc_msg_set_subjectPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dc_msg_t>,
              ffi.Pointer<ffi.Char>)>>('dc_msg_set_subject');
  late final _dc_msg_set_subject = _dc_msg_set_subjectPtr.asFunction<
      void Function(ffi.Pointer<dc_msg_t>, ffi.Pointer<ffi.Char>)>();

  void dc_msg_set_file_and_deduplicate(
    ffi.Pointer<dc_msg_t> msg,
    ffi.Pointer<ffi.Char> file,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Char> filemime,
  ) {
    return _dc_msg_set_file_and_deduplicate(
      msg,
      file,
      name,
      filemime,
    );
  }

  late final _dc_msg_set_file_and_deduplicatePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<dc_msg_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('dc_msg_set_file_and_deduplicate');
  late final _dc_msg_set_file_and_deduplicate =
      _dc_msg_set_file_and_deduplicatePtr.asFunction<
          void Function(ffi.Pointer<dc_msg_t>, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> dc_msg_get_file(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_get_file(
      msg,
    );
  }

  late final _dc_msg_get_filePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<dc_msg_t>)>>('dc_msg_get_file');
  late final _dc_msg_get_file = _dc_msg_get_filePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<dc_msg_t>)>();

  ffi.Pointer<ffi.Char> dc_msg_get_filename(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_get_filename(
      msg,
    );
  }

  late final _dc_msg_get_filenamePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<dc_msg_t>)>>('dc_msg_get_filename');
  late final _dc_msg_get_filename = _dc_msg_get_filenamePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<dc_msg_t>)>();

  ffi.Pointer<ffi.Char> dc_msg_get_filemime(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_get_filemime(
      msg,
    );
  }

  late final _dc_msg_get_filemimePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<dc_msg_t>)>>('dc_msg_get_filemime');
  late final _dc_msg_get_filemime = _dc_msg_get_filemimePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<dc_msg_t>)>();

  int dc_msg_get_filebytes(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_get_filebytes(
      msg,
    );
  }

  late final _dc_msg_get_filebytesPtr =
      _lookup<ffi.NativeFunction<ffi.Uint64 Function(ffi.Pointer<dc_msg_t>)>>(
          'dc_msg_get_filebytes');
  late final _dc_msg_get_filebytes = _dc_msg_get_filebytesPtr
      .asFunction<int Function(ffi.Pointer<dc_msg_t>)>();

  int dc_msg_get_width(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_get_width(
      msg,
    );
  }

  late final _dc_msg_get_widthPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<dc_msg_t>)>>(
          'dc_msg_get_width');
  late final _dc_msg_get_width =
      _dc_msg_get_widthPtr.asFunction<int Function(ffi.Pointer<dc_msg_t>)>();

  int dc_msg_get_height(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_get_height(
      msg,
    );
  }

  late final _dc_msg_get_heightPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<dc_msg_t>)>>(
          'dc_msg_get_height');
  late final _dc_msg_get_height =
      _dc_msg_get_heightPtr.asFunction<int Function(ffi.Pointer<dc_msg_t>)>();

  ffi.Pointer<dc_array_t> dc_get_fresh_msgs(
    ffi.Pointer<dc_context_t> ctx,
  ) {
    return _dc_get_fresh_msgs(
      ctx,
    );
  }

  late final _dc_get_fresh_msgsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_array_t> Function(
              ffi.Pointer<dc_context_t>)>>('dc_get_fresh_msgs');
  late final _dc_get_fresh_msgs = _dc_get_fresh_msgsPtr.asFunction<
      ffi.Pointer<dc_array_t> Function(ffi.Pointer<dc_context_t>)>();

  int dc_get_fresh_msg_cnt(
    ffi.Pointer<dc_context_t> ctx,
    int chat_id,
  ) {
    return _dc_get_fresh_msg_cnt(
      ctx,
      chat_id,
    );
  }

  late final _dc_get_fresh_msg_cntPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<dc_context_t>, ffi.Uint32)>>('dc_get_fresh_msg_cnt');
  late final _dc_get_fresh_msg_cnt = _dc_get_fresh_msg_cntPtr
      .asFunction<int Function(ffi.Pointer<dc_context_t>, int)>();

  void dc_marknoticed_chat(
    ffi.Pointer<dc_context_t> ctx,
    int chat_id,
  ) {
    return _dc_marknoticed_chat(
      ctx,
      chat_id,
    );
  }

  late final _dc_marknoticed_chatPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<dc_context_t>, ffi.Uint32)>>('dc_marknoticed_chat');
  late final _dc_marknoticed_chat = _dc_marknoticed_chatPtr
      .asFunction<void Function(ffi.Pointer<dc_context_t>, int)>();

  void dc_markseen_msgs(
    ffi.Pointer<dc_context_t> ctx,
    ffi.Pointer<ffi.Uint32> msg_ids,
    int msg_cnt,
  ) {
    return _dc_markseen_msgs(
      ctx,
      msg_ids,
      msg_cnt,
    );
  }

  late final _dc_markseen_msgsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dc_context_t>, ffi.Pointer<ffi.Uint32>,
              ffi.Int)>>('dc_markseen_msgs');
  late final _dc_markseen_msgs = _dc_markseen_msgsPtr.asFunction<
      void Function(ffi.Pointer<dc_context_t>, ffi.Pointer<ffi.Uint32>, int)>();

  void dc_delete_msgs(
    ffi.Pointer<dc_context_t> ctx,
    ffi.Pointer<ffi.Uint32> msg_ids,
    int msg_cnt,
  ) {
    return _dc_delete_msgs(
      ctx,
      msg_ids,
      msg_cnt,
    );
  }

  late final _dc_delete_msgsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dc_context_t>, ffi.Pointer<ffi.Uint32>,
              ffi.Int)>>('dc_delete_msgs');
  late final _dc_delete_msgs = _dc_delete_msgsPtr.asFunction<
      void Function(ffi.Pointer<dc_context_t>, ffi.Pointer<ffi.Uint32>, int)>();

  void dc_msg_set_quote(
    ffi.Pointer<dc_msg_t> msg,
    ffi.Pointer<dc_msg_t> quote,
  ) {
    return _dc_msg_set_quote(
      msg,
      quote,
    );
  }

  late final _dc_msg_set_quotePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dc_msg_t>,
              ffi.Pointer<dc_msg_t>)>>('dc_msg_set_quote');
  late final _dc_msg_set_quote = _dc_msg_set_quotePtr.asFunction<
      void Function(ffi.Pointer<dc_msg_t>, ffi.Pointer<dc_msg_t>)>();

  ffi.Pointer<dc_msg_t> dc_msg_get_quoted_msg(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_get_quoted_msg(
      msg,
    );
  }

  late final _dc_msg_get_quoted_msgPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_msg_t> Function(
              ffi.Pointer<dc_msg_t>)>>('dc_msg_get_quoted_msg');
  late final _dc_msg_get_quoted_msg = _dc_msg_get_quoted_msgPtr
      .asFunction<ffi.Pointer<dc_msg_t> Function(ffi.Pointer<dc_msg_t>)>();

  ffi.Pointer<ffi.Char> dc_msg_get_quoted_text(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_get_quoted_text(
      msg,
    );
  }

  late final _dc_msg_get_quoted_textPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<dc_msg_t>)>>('dc_msg_get_quoted_text');
  late final _dc_msg_get_quoted_text = _dc_msg_get_quoted_textPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<dc_msg_t>)>();

  void dc_forward_msgs(
    ffi.Pointer<dc_context_t> ctx,
    ffi.Pointer<ffi.Uint32> msg_ids,
    int msg_cnt,
    int chat_id,
  ) {
    return _dc_forward_msgs(
      ctx,
      msg_ids,
      msg_cnt,
      chat_id,
    );
  }

  late final _dc_forward_msgsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dc_context_t>, ffi.Pointer<ffi.Uint32>,
              ffi.Int, ffi.Uint32)>>('dc_forward_msgs');
  late final _dc_forward_msgs = _dc_forward_msgsPtr.asFunction<
      void Function(
          ffi.Pointer<dc_context_t>, ffi.Pointer<ffi.Uint32>, int, int)>();

  void dc_set_draft(
    ffi.Pointer<dc_context_t> ctx,
    int chat_id,
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_set_draft(
      ctx,
      chat_id,
      msg,
    );
  }

  late final _dc_set_draftPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dc_context_t>, ffi.Uint32,
              ffi.Pointer<dc_msg_t>)>>('dc_set_draft');
  late final _dc_set_draft = _dc_set_draftPtr.asFunction<
      void Function(ffi.Pointer<dc_context_t>, int, ffi.Pointer<dc_msg_t>)>();

  ffi.Pointer<dc_msg_t> dc_get_draft(
    ffi.Pointer<dc_context_t> ctx,
    int chat_id,
  ) {
    return _dc_get_draft(
      ctx,
      chat_id,
    );
  }

  late final _dc_get_draftPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_msg_t> Function(
              ffi.Pointer<dc_context_t>, ffi.Uint32)>>('dc_get_draft');
  late final _dc_get_draft = _dc_get_draftPtr.asFunction<
      ffi.Pointer<dc_msg_t> Function(ffi.Pointer<dc_context_t>, int)>();

  ffi.Pointer<dc_array_t> dc_search_msgs(
    ffi.Pointer<dc_context_t> ctx,
    int chat_id,
    ffi.Pointer<ffi.Char> query,
  ) {
    return _dc_search_msgs(
      ctx,
      chat_id,
      query,
    );
  }

  late final _dc_search_msgsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_array_t> Function(ffi.Pointer<dc_context_t>,
              ffi.Uint32, ffi.Pointer<ffi.Char>)>>('dc_search_msgs');
  late final _dc_search_msgs = _dc_search_msgsPtr.asFunction<
      ffi.Pointer<dc_array_t> Function(
          ffi.Pointer<dc_context_t>, int, ffi.Pointer<ffi.Char>)>();

  void dc_set_chat_visibility(
    ffi.Pointer<dc_context_t> ctx,
    int chat_id,
    int visibility,
  ) {
    return _dc_set_chat_visibility(
      ctx,
      chat_id,
      visibility,
    );
  }

  late final _dc_set_chat_visibilityPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dc_context_t>, ffi.Uint32,
              ffi.Int)>>('dc_set_chat_visibility');
  late final _dc_set_chat_visibility = _dc_set_chat_visibilityPtr
      .asFunction<void Function(ffi.Pointer<dc_context_t>, int, int)>();

  void dc_download_full_msg(
    ffi.Pointer<dc_context_t> ctx,
    int msg_id,
  ) {
    return _dc_download_full_msg(
      ctx,
      msg_id,
    );
  }

  late final _dc_download_full_msgPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<dc_context_t>, ffi.Int)>>('dc_download_full_msg');
  late final _dc_download_full_msg = _dc_download_full_msgPtr
      .asFunction<void Function(ffi.Pointer<dc_context_t>, int)>();

  int dc_msg_get_download_state(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_get_download_state(
      msg,
    );
  }

  late final _dc_msg_get_download_statePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<dc_msg_t>)>>(
          'dc_msg_get_download_state');
  late final _dc_msg_get_download_state = _dc_msg_get_download_statePtr
      .asFunction<int Function(ffi.Pointer<dc_msg_t>)>();

  int dc_resend_msgs(
    ffi.Pointer<dc_context_t> ctx,
    ffi.Pointer<ffi.Uint32> msg_ids,
    int msg_cnt,
  ) {
    return _dc_resend_msgs(
      ctx,
      msg_ids,
      msg_cnt,
    );
  }

  late final _dc_resend_msgsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<dc_context_t>, ffi.Pointer<ffi.Uint32>,
              ffi.Int)>>('dc_resend_msgs');
  late final _dc_resend_msgs = _dc_resend_msgsPtr.asFunction<
      int Function(ffi.Pointer<dc_context_t>, ffi.Pointer<ffi.Uint32>, int)>();

  ffi.Pointer<ffi.Char> dc_msg_get_error(
    ffi.Pointer<dc_msg_t> msg,
  ) {
    return _dc_msg_get_error(
      msg,
    );
  }

  late final _dc_msg_get_errorPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<dc_msg_t>)>>('dc_msg_get_error');
  late final _dc_msg_get_error = _dc_msg_get_errorPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<dc_msg_t>)>();

  ffi.Pointer<dc_array_t> dc_get_contacts(
    ffi.Pointer<dc_context_t> ctx,
    int flags,
    ffi.Pointer<ffi.Char> query,
  ) {
    return _dc_get_contacts(
      ctx,
      flags,
      query,
    );
  }

  late final _dc_get_contactsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_array_t> Function(ffi.Pointer<dc_context_t>,
              ffi.Uint32, ffi.Pointer<ffi.Char>)>>('dc_get_contacts');
  late final _dc_get_contacts = _dc_get_contactsPtr.asFunction<
      ffi.Pointer<dc_array_t> Function(
          ffi.Pointer<dc_context_t>, int, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<dc_array_t> dc_get_blocked_contacts(
    ffi.Pointer<dc_context_t> ctx,
  ) {
    return _dc_get_blocked_contacts(
      ctx,
    );
  }

  late final _dc_get_blocked_contactsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<dc_array_t> Function(
              ffi.Pointer<dc_context_t>)>>('dc_get_blocked_contacts');
  late final _dc_get_blocked_contacts = _dc_get_blocked_contactsPtr.asFunction<
      ffi.Pointer<dc_array_t> Function(ffi.Pointer<dc_context_t>)>();

  int dc_delete_contact(
    ffi.Pointer<dc_context_t> ctx,
    int contact_id,
  ) {
    return _dc_delete_contact(
      ctx,
      contact_id,
    );
  }

  late final _dc_delete_contactPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<dc_context_t>, ffi.Uint32)>>('dc_delete_contact');
  late final _dc_delete_contact = _dc_delete_contactPtr
      .asFunction<int Function(ffi.Pointer<dc_context_t>, int)>();
}

final class __mbstate_t extends ffi.Union {
  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> __mbstate8;

  @ffi.LongLong()
  external int _mbstateL;
}

final class __darwin_pthread_handler_rec extends ffi.Struct {
  external ffi
      .Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>
      __routine;

  external ffi.Pointer<ffi.Void> __arg;

  external ffi.Pointer<__darwin_pthread_handler_rec> __next;
}

final class _opaque_pthread_attr_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_cond_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([40])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_condattr_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_mutex_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_mutexattr_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_once_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_rwlock_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([192])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_rwlockattr_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([16])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  external ffi.Pointer<__darwin_pthread_handler_rec> __cleanup_stack;

  @ffi.Array.multi([8176])
  external ffi.Array<ffi.Char> __opaque;
}

final class dc_context extends ffi.Opaque {}

final class dc_event extends ffi.Opaque {}

final class dc_event_emitter extends ffi.Opaque {}

final class dc_accounts extends ffi.Opaque {}

final class dc_array extends ffi.Opaque {}

final class dc_chat extends ffi.Opaque {}

final class dc_chatlist extends ffi.Opaque {}

final class dc_contact extends ffi.Opaque {}

final class dc_msg extends ffi.Opaque {}

typedef dc_accounts_t = dc_accounts;
typedef dc_array_t = dc_array;
typedef dc_context_t = dc_context;
typedef dc_event_emitter_t = dc_event_emitter;
typedef dc_chatlist_t = dc_chatlist;
typedef dc_event_t = dc_event;
typedef dc_msg_t = dc_msg;
typedef dc_chat_t = dc_chat;
typedef dc_contact_t = dc_contact;

const int __has_safe_buffers = 1;

const int __DARWIN_ONLY_64_BIT_INO_T = 1;

const int __DARWIN_ONLY_UNIX_CONFORMANCE = 1;

const int __DARWIN_ONLY_VERS_1050 = 1;

const int __DARWIN_UNIX03 = 1;

const int __DARWIN_64_BIT_INO_T = 1;

const int __DARWIN_VERS_1050 = 1;

const int __DARWIN_NON_CANCELABLE = 0;

const String __DARWIN_SUF_EXTSN = '\$DARWIN_EXTSN';

const int __DARWIN_C_ANSI = 4096;

const int __DARWIN_C_FULL = 900000;

const int __DARWIN_C_LEVEL = 900000;

const int __STDC_WANT_LIB_EXT1__ = 1;

const int __DARWIN_NO_LONG_LONG = 0;

const int _DARWIN_FEATURE_64_BIT_INODE = 1;

const int _DARWIN_FEATURE_ONLY_64_BIT_INODE = 1;

const int _DARWIN_FEATURE_ONLY_VERS_1050 = 1;

const int _DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE = 1;

const int _DARWIN_FEATURE_UNIX_CONFORMANCE = 3;

const int __has_ptrcheck = 0;

const int __DARWIN_NULL = 0;

const int __PTHREAD_SIZE__ = 8176;

const int __PTHREAD_ATTR_SIZE__ = 56;

const int __PTHREAD_MUTEXATTR_SIZE__ = 8;

const int __PTHREAD_MUTEX_SIZE__ = 56;

const int __PTHREAD_CONDATTR_SIZE__ = 8;

const int __PTHREAD_COND_SIZE__ = 40;

const int __PTHREAD_ONCE_SIZE__ = 8;

const int __PTHREAD_RWLOCK_SIZE__ = 192;

const int __PTHREAD_RWLOCKATTR_SIZE__ = 16;

const int __DARWIN_WCHAR_MAX = 2147483647;

const int __DARWIN_WCHAR_MIN = -2147483648;

const int __DARWIN_WEOF = -1;

const int _FORTIFY_SOURCE = 2;

const int NULL = 0;

const int USER_ADDR_NULL = 0;

const int __WORDSIZE = 64;

const int INT8_MAX = 127;

const int INT16_MAX = 32767;

const int INT32_MAX = 2147483647;

const int INT64_MAX = 9223372036854775807;

const int INT8_MIN = -128;

const int INT16_MIN = -32768;

const int INT32_MIN = -2147483648;

const int INT64_MIN = -9223372036854775808;

const int UINT8_MAX = 255;

const int UINT16_MAX = 65535;

const int UINT32_MAX = 4294967295;

const int UINT64_MAX = -1;

const int INT_LEAST8_MIN = -128;

const int INT_LEAST16_MIN = -32768;

const int INT_LEAST32_MIN = -2147483648;

const int INT_LEAST64_MIN = -9223372036854775808;

const int INT_LEAST8_MAX = 127;

const int INT_LEAST16_MAX = 32767;

const int INT_LEAST32_MAX = 2147483647;

const int INT_LEAST64_MAX = 9223372036854775807;

const int UINT_LEAST8_MAX = 255;

const int UINT_LEAST16_MAX = 65535;

const int UINT_LEAST32_MAX = 4294967295;

const int UINT_LEAST64_MAX = -1;

const int INT_FAST8_MIN = -128;

const int INT_FAST16_MIN = -32768;

const int INT_FAST32_MIN = -2147483648;

const int INT_FAST64_MIN = -9223372036854775808;

const int INT_FAST8_MAX = 127;

const int INT_FAST16_MAX = 32767;

const int INT_FAST32_MAX = 2147483647;

const int INT_FAST64_MAX = 9223372036854775807;

const int UINT_FAST8_MAX = 255;

const int UINT_FAST16_MAX = 65535;

const int UINT_FAST32_MAX = 4294967295;

const int UINT_FAST64_MAX = -1;

const int INTPTR_MAX = 9223372036854775807;

const int INTPTR_MIN = -9223372036854775808;

const int UINTPTR_MAX = -1;

const int INTMAX_MAX = 9223372036854775807;

const int UINTMAX_MAX = -1;

const int INTMAX_MIN = -9223372036854775808;

const int PTRDIFF_MIN = -9223372036854775808;

const int PTRDIFF_MAX = 9223372036854775807;

const int SIZE_MAX = -1;

const int RSIZE_MAX = 9223372036854775807;

const int WCHAR_MAX = 2147483647;

const int WCHAR_MIN = -2147483648;

const int WINT_MIN = -2147483648;

const int WINT_MAX = 2147483647;

const int SIG_ATOMIC_MIN = -2147483648;

const int SIG_ATOMIC_MAX = 2147483647;

const int DC_MSG_UNDEFINED = 0;

const int DC_MSG_TEXT = 10;

const int DC_MSG_IMAGE = 20;

const int DC_MSG_GIF = 21;

const int DC_MSG_STICKER = 23;

const int DC_MSG_AUDIO = 40;

const int DC_MSG_VOICE = 41;

const int DC_MSG_VIDEO = 50;

const int DC_MSG_FILE = 60;

const int DC_MSG_CALL = 71;

const int DC_MSG_WEBXDC = 80;

const int DC_MSG_VCARD = 90;

const int DC_INFO_UNKNOWN = 0;

const int DC_INFO_GROUP_NAME_CHANGED = 2;

const int DC_INFO_GROUP_IMAGE_CHANGED = 3;

const int DC_INFO_MEMBER_ADDED_TO_GROUP = 4;

const int DC_INFO_MEMBER_REMOVED_FROM_GROUP = 5;

const int DC_INFO_AUTOCRYPT_SETUP_MESSAGE = 6;

const int DC_INFO_SECURE_JOIN_MESSAGE = 7;

const int DC_INFO_LOCATIONSTREAMING_ENABLED = 8;

const int DC_INFO_LOCATION_ONLY = 9;

const int DC_INFO_EPHEMERAL_TIMER_CHANGED = 10;

const int DC_INFO_PROTECTION_ENABLED = 11;

const int DC_INFO_INVALID_UNENCRYPTED_MAIL = 13;

const int DC_INFO_WEBXDC_INFO_MESSAGE = 32;

const int DC_INFO_CHAT_E2EE = 50;

const int DC_STATE_UNDEFINED = 0;

const int DC_STATE_IN_FRESH = 10;

const int DC_STATE_IN_NOTICED = 13;

const int DC_STATE_IN_SEEN = 16;

const int DC_STATE_OUT_PREPARING = 18;

const int DC_STATE_OUT_DRAFT = 19;

const int DC_STATE_OUT_PENDING = 20;

const int DC_STATE_OUT_FAILED = 24;

const int DC_STATE_OUT_DELIVERED = 26;

const int DC_STATE_OUT_MDN_RCVD = 28;

const int DC_MSG_NO_ID = 0;

const int DC_MSG_ID_MARKER1 = 1;

const int DC_MSG_ID_DAYMARKER = 9;

const int DC_VIDEOCHATTYPE_UNKNOWN = 0;

const int DC_VIDEOCHATTYPE_BASICWEBRTC = 1;

const int DC_CHAT_TYPE_UNDEFINED = 0;

const int DC_CHAT_TYPE_SINGLE = 100;

const int DC_CHAT_TYPE_GROUP = 120;

const int DC_CHAT_TYPE_MAILINGLIST = 140;

const int DC_CHAT_TYPE_OUT_BROADCAST = 160;

const int DC_CHAT_TYPE_IN_BROADCAST = 165;

const int DC_CHAT_NO_CHAT = 0;

const int DC_CHAT_ID_ARCHIVED_LINK = 6;

const int DC_CHAT_ID_ALLDONE_HINT = 7;

const int DC_CHAT_ID_LAST_SPECIAL = 9;

const int DC_CONTACT_ID_SELF = 1;

const int DC_CONTACT_ID_INFO = 2;

const int DC_CONTACT_ID_DEVICE = 5;

const int DC_CONTACT_ID_LAST_SPECIAL = 9;

const int DC_EVENT_INFO = 100;

const int DC_EVENT_WARNING = 300;

const int DC_EVENT_ERROR = 400;

const int DC_EVENT_ERROR_SELF_NOT_IN_GROUP = 410;

const int DC_EVENT_MSGS_CHANGED = 2000;

const int DC_EVENT_REACTIONS_CHANGED = 2001;

const int DC_EVENT_INCOMING_REACTION = 2002;

const int DC_EVENT_INCOMING_WEBXDC_NOTIFY = 2003;

const int DC_EVENT_MSGS_NOTICED = 2008;

const int DC_EVENT_INCOMING_MSG = 2005;

const int DC_EVENT_INCOMING_MSG_BUNCH = 2006;

const int DC_EVENT_MSG_DELIVERED = 2010;

const int DC_EVENT_MSG_FAILED = 2012;

const int DC_EVENT_MSG_READ = 2015;

const int DC_EVENT_CHAT_MODIFIED = 2020;

const int DC_EVENT_CHAT_EPHEMERAL_TIMER_MODIFIED = 2021;

const int DC_EVENT_CHAT_DELETED = 2023;

const int DC_EVENT_CONTACTS_CHANGED = 2030;

const int DC_EVENT_LOCATION_CHANGED = 2035;

const int DC_EVENT_CONFIGURE_PROGRESS = 2041;

const int DC_EVENT_IMEX_PROGRESS = 2051;

const int DC_EVENT_IMEX_FILE_WRITTEN = 2052;

const int DC_EVENT_SECUREJOIN_INVITER_PROGRESS = 2060;

const int DC_EVENT_SECUREJOIN_JOINER_PROGRESS = 2061;

const int DC_EVENT_CONNECTIVITY_CHANGED = 2100;

const int DC_EVENT_SELFAVATAR_CHANGED = 2110;

const int DC_EVENT_WEBXDC_STATUS_UPDATE = 2120;

const int DC_EVENT_WEBXDC_INSTANCE_DELETED = 2121;

const int DC_EVENT_WEBXDC_REALTIME_DATA = 2150;

const int DC_EVENT_ACCOUNTS_BACKGROUND_FETCH_DONE = 2200;

const int DC_EVENT_CHANNEL_OVERFLOW = 2400;

const int DC_EVENT_INCOMING_CALL = 2550;

const int DC_EVENT_INCOMING_CALL_ACCEPTED = 2560;

const int DC_EVENT_OUTGOING_CALL_ACCEPTED = 2570;

const int DC_EVENT_CALL_ENDED = 2580;

const int DC_IMEX_EXPORT_SELF_KEYS = 1;

const int DC_IMEX_IMPORT_SELF_KEYS = 2;

const int DC_IMEX_EXPORT_BACKUP = 11;

const int DC_IMEX_IMPORT_BACKUP = 12;

const int DC_GCM_ADDDAYMARKER = 1;

const int DC_QR_ASK_VERIFYCONTACT = 200;

const int DC_QR_ASK_VERIFYGROUP = 202;

const int DC_QR_ASK_JOIN_BROADCAST = 204;

const int DC_QR_FPR_OK = 210;

const int DC_QR_FPR_MISMATCH = 220;

const int DC_QR_FPR_WITHOUT_ADDR = 230;

const int DC_QR_ACCOUNT = 250;

const int DC_QR_BACKUP2 = 252;

const int DC_QR_BACKUP_TOO_NEW = 255;

const int DC_QR_WEBRTC = 260;

const int DC_QR_PROXY = 271;

const int DC_QR_ADDR = 320;

const int DC_QR_TEXT = 330;

const int DC_QR_URL = 332;

const int DC_QR_ERROR = 400;

const int DC_QR_WITHDRAW_VERIFYCONTACT = 500;

const int DC_QR_WITHDRAW_VERIFYGROUP = 502;

const int DC_QR_WITHDRAW_JOINBROADCAST = 504;

const int DC_QR_REVIVE_VERIFYCONTACT = 510;

const int DC_QR_REVIVE_VERIFYGROUP = 512;

const int DC_QR_REVIVE_JOINBROADCAST = 514;

const int DC_QR_LOGIN = 520;

const int DC_SOCKET_AUTO = 0;

const int DC_SOCKET_SSL = 1;

const int DC_SOCKET_STARTTLS = 2;

const int DC_SOCKET_PLAIN = 3;

const int DC_SHOW_EMAILS_OFF = 0;

const int DC_SHOW_EMAILS_ACCEPTED_CONTACTS = 1;

const int DC_SHOW_EMAILS_ALL = 2;

const int DC_MEDIA_QUALITY_BALANCED = 0;

const int DC_MEDIA_QUALITY_WORSE = 1;

const int DC_CONNECTIVITY_NOT_CONNECTED = 1000;

const int DC_CONNECTIVITY_CONNECTING = 2000;

const int DC_CONNECTIVITY_WORKING = 3000;

const int DC_CONNECTIVITY_CONNECTED = 4000;

const int DC_DOWNLOAD_DONE = 0;

const int DC_DOWNLOAD_AVAILABLE = 10;

const int DC_DOWNLOAD_FAILURE = 20;

const int DC_DOWNLOAD_UNDECIPHERABLE = 30;

const int DC_DOWNLOAD_IN_PROGRESS = 1000;

const int DC_CHAT_VISIBILITY_NORMAL = 0;

const int DC_CHAT_VISIBILITY_ARCHIVED = 1;

const int DC_CHAT_VISIBILITY_PINNED = 2;

const int DC_GCL_VERIFIED_ONLY = 1;

const int DC_GCL_ADD_SELF = 2;

const int DC_GCL_ADDRESS = 4;

const int DC_GCL_ARCHIVED_ONLY = 1;

const int DC_GCL_NO_SPECIALS = 2;

const int DC_GCL_ADD_ALLDONE_HINT = 4;

const int DC_GCL_FOR_FORWARDING = 8;
