targets:
  $default:
    builders:
      drift_dev:
        options:
          store_date_time_values_as_text: true
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
      json_serializable:
        options:
          field_rename: snake
          checked: true