# Rust/native assets for packages like delta_ffi are compiled via code_assets when
# `dart run build_runner build --delete-conflicting-outputs` runs. Prebuilt
# binaries are never checked into the repository.
targets:
  $default:
    builders:
      drift_dev:
        generate_for:
          - lib/src/storage/**
        options:
          store_date_time_values_as_text: true
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
      json_serializable:
        options:
          field_rename: snake
          checked: true
