definitions:
  scripts:
    - &shorebird_install
      name: Install Shorebird
      script: |
        # Install Shorebird
        curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash

        # Add Shorebird to PATH
        echo PATH="$HOME/.shorebird/bin:$PATH" >> $CM_ENV
    - &shorebird_install_windows
      name: Install Shorebird Windows
      script: |
        Set-ExecutionPolicy RemoteSigned -scope CurrentUser
        iwr -UseBasicParsing 'https://raw.githubusercontent.com/shorebirdtech/install/main/install.ps1'|iex
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
        Add-Content -Path $env:CM_ENV -Value "PATH=$env:Path"
    - &openssl_install_windows
      name: Install OpenSSL Windows
      script: |
        choco install openssl --version 3.1.1 -y
    - &refresh_path_windows
      name: Refresh Path
      script: |
        Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
        refreshenv
    - &fetch_dependencies
      name: Fetch Dependencies
      script: |
        flutter clean
        flutter pub get
        flutter doctor
        flutter devices
        flutter emulators
    - &build_runner
      name: Build Runner
      script: |
        flutter pub get
        dart run build_runner build --delete-conflicting-outputs
    - &diagnose_git_remotes
      name: Diagnose Git Remotes
      script: |
        cat ~/.ssh/config 
        cat .git/config 
        git remote -v
    - &github_release_create_android
      name: Create Android GitHub Release
      script: |
        git remote set-url origin https://github.com/axichat/axichat.git
        git remote -v
        
        echo $GITHUB_TOKEN | gh auth login --with-token
        
        sh -c '
          [ -n "$CM_TAG" ] || { echo "CM_TAG is empty"; exit 1; }

          # optional: set this if you want to be explicit about repo
          # REPO="owner/name"

          if gh release view "$CM_TAG" >/dev/null 2>&1; then
            echo "Release exists, skipping."
          else
            gh release create "$CM_TAG" --verify-tag --notes-from-tag --title "axichat $CM_TAG"
          fi
        '
    - &github_release_upload_android
      name: Upload to Android GitHub Releases
      script: |
        git remote set-url origin https://github.com/axichat/axichat.git
        git remote -v
        
        echo $GITHUB_TOKEN | gh auth login --with-token
        
        gh release upload $CM_TAG \
        build/app/outputs/flutter-apk/*.apk \
        build/app/outputs/flutter-apk/*.sha1
    - &github_release_create_windows
      name: Create Windows GitHub Release
      script: |
        git remote set-url origin https://github.com/axichat/axichat.git
        git remote -v
        
        echo $env:GITHUB_TOKEN | gh auth login --with-token
        
        $ErrorActionPreference = 'Stop'
        if ([string]::IsNullOrWhiteSpace($env:CM_TAG)) { throw "CM_TAG is empty (not a tag build?)" }
  
        $json = gh release view $env:CM_TAG --json tagName 2>$null
        $ghOk = ($LASTEXITCODE -eq 0)
  
        if ($ghOk -and ($json | ConvertFrom-Json).tagName -eq $env:CM_TAG) {
          Write-Host "Release exists, skipping."
        } else {
          gh release create $env:CM_TAG --verify-tag --notes-from-tag --title "axichat $($env:CM_TAG)"
        }
    - &github_release_upload_windows
      name: Upload to Windows GitHub Releases
      script: |
        git remote set-url origin https://github.com/axichat/axichat.git
        git remote -v
        
        echo $env:GITHUB_TOKEN | gh auth login --with-token
        
        gh release upload $env:CM_TAG 'build\windows\x64\runner\release.zip#axichat windows'
    - &github_release_upload_linux
      name: Upload to Linux GitHub Releases
      script: |
        git remote set-url origin https://github.com/axichat/axichat.git
        git remote -v

        echo $GITHUB_TOKEN | gh auth login --with-token

        gh release upload $CM_TAG dist/axichat-linux-$CM_TAG.tar.gz#axichat-linux

workflows:
  test-workflow:
    name: Test Only Workflow
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: 'dev'
          include: true
          source: true
    when:
      changeset:
        includes:
          - '.'
        excludes:
          - '**/*.md'
          - 'metadata/*'
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      ubuntu: 24.04
      flutter: stable
      groups:
        - integration_test
        - chatmail_provisioning # Provides CHATMAIL_SHARED_SECRET for dart-define builds/tests.
      android_signing:
        - AXICHAT_UPLOAD_KEY
    scripts:
      - *fetch_dependencies
      - *build_runner
      - name: Unit Tests
        script: |
          mkdir -p test-results
          flutter test \
          --dart-define=CHATMAIL_SHARED_SECRET=$CHATMAIL_SHARED_SECRET \
          --machine > test-results/flutter.json
        test_report: test-results/flutter.json
      - name: Integration Tests
        script: |
          mkdir -p test-results
          flutter emulators --launch emulator-35 
          adb wait-for-device
          flutter test -d emulator-5554 integration_test \
          --dart-define=CHATMAIL_SHARED_SECRET=$CHATMAIL_SHARED_SECRET \
          --dart-define=USERNAME=$USERNAME \
          --dart-define=PASSWORD=$PASSWORD \
          --dart-define=CONTACT_JID=$CONTACT_JID \
          --machine > test-results/flutter.json
        test_report: test-results/flutter.json
  release-android-workflow:
    name: Android Release Workflow
    triggering:
      events:
        - tag
      branch_patterns:
        - pattern: 'master'
          include: true
          source: true
      tag_patterns:
        - pattern: 'v+([0-9]).+([0-9]).+([0-9])'
          include: true
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      ubuntu: 24.04
      flutter: stable
      groups:
        - shorebird # TODO: Store SHOREBIRD_TOKEN from `shorebird login:ci` in this group.
        - github # TODO: Provide a GitHub PAT as GITHUB_TOKEN for release publishing.
        - chatmail_provisioning # CHATMAIL_SHARED_SECRET for provisioning glue service.
      android_signing:
        - AXICHAT_UPLOAD_KEY # TODO: Upload the release keystore/certs and link it as AXICHAT_UPLOAD_KEY.
    scripts:
      - *shorebird_install
      - *fetch_dependencies
      - *build_runner
      - name: Shorebird Release
        script: |
          shorebird release android --flavor production --artifact=apk \
          --dart-define=CHATMAIL_SHARED_SECRET=$CHATMAIL_SHARED_SECRET
      - *github_release_create_android
      - *github_release_upload_android
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/flutter-apk/*.sha1
  patch-android-workflow:
    name: Android Patch Workflow
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      ubuntu: 24.04
      flutter: stable
      groups:
        - shorebird # TODO: Codemagic must expose SHOREBIRD_TOKEN for patching builds.
        - chatmail_provisioning # CHATMAIL_SHARED_SECRET for provisioning glue service.
    inputs:
      release_version:
        description: The release version to patch
    scripts:
      - *shorebird_install
      - *fetch_dependencies
      - *build_runner
      - name: Shorebird Patch
        script: |
          shorebird patch android --flavor production \
          --release-version=${{ inputs.release_version }} \
          --dart-define=CHATMAIL_SHARED_SECRET=$CHATMAIL_SHARED_SECRET
  dev-release-android-workflow:
    name: Android Development Release Workflow
    triggering:
      events:
        - tag
      branch_patterns:
        - pattern: 'dev'
          include: true
          source: true
      tag_patterns:
        - pattern: 'v+([0-9]).+([0-9]).+([0-9])-dev'
          include: true
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      ubuntu: 24.04
      flutter: stable
      groups:
        - shorebird # TODO: Store SHOREBIRD_TOKEN from `shorebird login:ci` in this group.
        - github # TODO: Provide GITHUB_TOKEN via Codemagic's github group before tagging dev releases.
        - chatmail_provisioning # CHATMAIL_SHARED_SECRET for provisioning glue service.
      android_signing:
        - AXICHAT_UPLOAD_KEY # TODO: Upload a dev keystore or reuse the production key via Codemagic secrets.
    scripts:
      - *shorebird_install
      - *fetch_dependencies
      - *build_runner
      - name: Shorebird Release Development
        script: |
          shorebird release android --flavor development --artifact=apk \
          --dart-define=CHATMAIL_SHARED_SECRET=$CHATMAIL_SHARED_SECRET
      - *github_release_create_android
      - *github_release_upload_android
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/flutter-apk/*.sha1
  dev-patch-android-workflow:
    name: Android Development Patch Workflow
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      ubuntu: 24.04
      flutter: stable
      groups:
        - shorebird # TODO: Codemagic group must include SHOREBIRD_TOKEN for dev patching.
        - chatmail_provisioning # CHATMAIL_SHARED_SECRET for provisioning glue service.
    inputs:
      release_version:
        description: The release version to patch
    scripts:
      - *shorebird_install
      - *fetch_dependencies
      - *build_runner
      - name: Shorebird Patch Development
        script: |
          shorebird patch android --flavor development \
          --release-version=${{ inputs.release_version }} \
          --dart-define=CHATMAIL_SHARED_SECRET=$CHATMAIL_SHARED_SECRET
  release-windows-workflow:
    name: Windows Release Workflow
    triggering:
      events:
        - tag
      branch_patterns:
        - pattern: 'master'
          include: true
          source: true
      tag_patterns:
        - pattern: 'v+([0-9]).+([0-9]).+([0-9])'
          include: true
    max_build_duration: 60
    instance_type: windows_x2
    environment:
      flutter: stable
      groups:
        - shorebird # TODO: Store SHOREBIRD_TOKEN from `shorebird login:ci` for Windows releases.
        - github # TODO: Provide a GitHub PAT via GITHUB_TOKEN for desktop uploads.
        - chatmail_provisioning # CHATMAIL_SHARED_SECRET for provisioning glue service.
    scripts:
      - *shorebird_install_windows
      - *fetch_dependencies
      - *build_runner
      - *openssl_install_windows
      - *refresh_path_windows
      - name: Configure for Windows
        script: |
          flutter config --enable-windows-desktop
      - name: Shorebird Release
        script: |
          & $HOME\.shorebird\bin\shorebird.ps1 release windows --flavor production `
            --dart-define=CHATMAIL_SHARED_SECRET=$env:CHATMAIL_SHARED_SECRET
      - name: Export bundle
        script: |
          Copy-Item -Path C:\Windows\System32\msvcp140.dll -Destination build/windows/x64/runner/Release 
          Copy-Item -Path C:\Windows\System32\vcruntime140.dll -Destination build/windows/x64/runner/Release 
          Copy-Item -Path C:\Windows\System32\vcruntime140_1.dll -Destination build/windows/x64/runner/Release 
          cd build/windows/x64/runner/Release
          7z a -r ../release.zip ./*
      - *github_release_create_windows
      - *github_release_upload_windows
    artifacts:
      - build\windows\x64\runner\release.zip
  release-linux-workflow:
    name: Linux Release Workflow
    triggering:
      events:
        - tag
      branch_patterns:
        - pattern: 'master'
          include: true
          source: true
      tag_patterns:
        - pattern: 'v+([0-9]).+([0-9]).+([0-9])'
          include: true
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      ubuntu: 24.04
      flutter: stable
      groups:
        - shorebird # TODO: Store SHOREBIRD_TOKEN for Linux desktop releases.
        - github # TODO: Provide GITHUB_TOKEN with repo scope for Linux artifact uploads.
        - chatmail_provisioning # CHATMAIL_SHARED_SECRET for provisioning glue service.
    scripts:
      - *shorebird_install
      - *fetch_dependencies
      - *build_runner
      - name: Configure for Linux
        script: |
          flutter config --enable-linux-desktop
      - name: Shorebird Release Linux
        script: |
          shorebird release linux --flavor production \
          --dart-define=CHATMAIL_SHARED_SECRET=$CHATMAIL_SHARED_SECRET
      - name: Package Linux Bundle
        script: |
          mkdir -p dist
          tar -czf dist/axichat-linux-$CM_TAG.tar.gz -C build/linux/x64/release/bundle .
      - *github_release_create_android
      - *github_release_upload_linux
    artifacts:
      - dist/axichat-linux-*.tar.gz
