definitions:
  scripts:
    - &shorebird_install
      name: Install Shorebird
      script: |
        # Install Shorebird
        curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash

        # Add Shorebird to PATH
        echo PATH="$HOME/.shorebird/bin:$PATH" >> $CM_ENV
    - &fetch_dependencies
      name: Fetch Dependencies
      script: |
        flutter clean
        flutter pub get
        flutter doctor
        flutter devices
        flutter emulators
    - &build_runner
      name: Build Runner
      script: |
        dart run build_runner build

workflows:
  test-workflow:
    name: Test Only Workflow
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: 'dev'
          include: true
          source: true
    when:
      changeset:
        includes:
          - '.'
        excludes:
          - '**/*.md'
          - 'metadata/*'
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      ubuntu: 24.04
      flutter: stable
      groups:
        - integration_test
      android_signing:
        - AXICHAT_UPLOAD_KEY
    scripts:
      - *fetch_dependencies
      - *build_runner
      - name: Unit Tests
        script: |
          mkdir -p test-results
          flutter test --machine > test-results/flutter.json
        test_report: test-results/flutter.json
      - name: Integration Tests
        script: |
          mkdir -p test-results
          flutter emulators --launch emulator-35 
          adb wait-for-device
          flutter test -d emulator-5554 integration_test \
          --dart-define=USERNAME=$USERNAME \
          --dart-define=PASSWORD=$PASSWORD \
          --dart-define=CONTACT_JID=$CONTACT_JID \
          --machine > test-results/flutter.json
        test_report: test-results/flutter.json
  release-android-workflow:
    name: Android Release Workflow
    triggering:
      events:
        - tag
      branch_patterns:
        - pattern: 'master'
          include: true
          source: true
      tag_patterns:
        - pattern: 'v+([0-9]).+([0-9]).+([0-9])'
          include: true
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      ubuntu: 24.04
      flutter: stable
      groups:
        - shorebird
        - github
      android_signing:
        - AXICHAT_UPLOAD_KEY
    scripts:
      - *build_runner
      - *shorebird_install
      - *fetch_dependencies
      - name: Shorebird Release
        script: |
          shorebird release android --flavor production --artifact=apk
      - name: Publish to GitHub
        script: |
          #!/usr/bin/env zsh
          
          # Publish only for tag builds
          if [ -z ${CM_TAG} ]; then
            echo "Not a tag build, will not publish GitHub release"
            exit 0
          fi
          
          gh release create "${CM_TAG}" \
            --title "axichat ${CM_TAG}" \
            build/app/outputs/flutter-apk/app-production-release.apk
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/flutter-apk/*.sha1
  patch-android-workflow:
    name: Android Patch Workflow
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      ubuntu: 24.04
      flutter: stable
      groups:
        - shorebird
    inputs:
      release_version:
        description: The release version to patch
    scripts:
      - *build_runner
      - *shorebird_install
      - *fetch_dependencies
      - name: Shorebird Patch
        script: |
          shorebird patch android --flavor production \
          --artifact=apk \
          --release-version=${{ inputs.release_version }}
  dev-release-android-workflow:
    name: Android Development Release Workflow
    triggering:
      events:
        - tag
      branch_patterns:
        - pattern: 'dev'
          include: true
          source: true
      tag_patterns:
        - pattern: 'v+([0-9]).+([0-9]).+([0-9])-dev'
          include: true
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      ubuntu: 24.04
      flutter: stable
      groups:
        - shorebird
        - github
      android_signing:
        - AXICHAT_UPLOAD_KEY
    scripts:
      - *build_runner
      - *shorebird_install
      - *fetch_dependencies
      - name: Shorebird Release Development
        script: |
          shorebird release android --flavor development --artifact=apk
      - name: Publish to GitHub
        script: |
          echo $GITHUB_TOKEN | gh auth login --with-token
          
          gh release create $CM_TAG \
          --verify-tag \
          --notes-from-tag \
          --repo github.com/axichat/axichat \
          build/app/outputs/flutter-apk/app-development-release.apk
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/flutter-apk/*.sha1
  dev-patch-android-workflow:
    name: Android Development Patch Workflow
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      ubuntu: 24.04
      flutter: stable
      groups:
        - shorebird
    inputs:
      release_version:
        description: The release version to patch
    scripts:
      - *build_runner
      - *shorebird_install
      - *fetch_dependencies
      - name: Shorebird Patch Development
        script: |
          shorebird patch android --flavor development \
          --artifact=apk \
          --release-version=${{ inputs.release_version }}
          
